// This file is auto-generated by @hey-api/openapi-ts

export const $ActionType = {
  type: 'string',
  enum: ['add_tag'],
  title: 'ActionType',
  description: 'Types of actions a rule can perform.',
} as const

export const $ApplyRulesRequest = {
  properties: {
    statement_id: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid',
        },
        {
          type: 'null',
        },
      ],
      title: 'Statement Id',
    },
    transaction_ids: {
      anyOf: [
        {
          items: {
            type: 'string',
            format: 'uuid',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Transaction Ids',
    },
  },
  type: 'object',
  title: 'ApplyRulesRequest',
  description: 'Input for the apply rules endpoint.',
} as const

export const $ApplyRulesResponse = {
  properties: {
    transactions_processed: {
      type: 'integer',
      title: 'Transactions Processed',
    },
    tags_applied: {
      type: 'integer',
      title: 'Tags Applied',
    },
    details: {
      items: {
        $ref: '#/components/schemas/TransactionMatch',
      },
      type: 'array',
      title: 'Details',
    },
  },
  type: 'object',
  required: ['transactions_processed', 'tags_applied', 'details'],
  title: 'ApplyRulesResponse',
  description: 'Output for the apply rules endpoint.',
} as const

export const $BatchCurrencyConversionRequest = {
  properties: {
    conversions: {
      items: {
        $ref: '#/components/schemas/CurrencyConversionRequest',
      },
      type: 'array',
      title: 'Conversions',
    },
  },
  type: 'object',
  required: ['conversions'],
  title: 'BatchCurrencyConversionRequest',
  description: 'Request model for converting multiple amounts.',
} as const

export const $BatchCurrencyConversionResponse = {
  properties: {
    results: {
      items: {
        $ref: '#/components/schemas/CurrencyConversionResponse',
      },
      type: 'array',
      title: 'Results',
    },
  },
  type: 'object',
  required: ['results'],
  title: 'BatchCurrencyConversionResponse',
  description: 'Response model for batch currency conversion.',
} as const

export const $BatchTransactionTagsRequest = {
  properties: {
    transaction_ids: {
      items: {
        type: 'string',
        format: 'uuid',
      },
      type: 'array',
      title: 'Transaction Ids',
    },
  },
  type: 'object',
  required: ['transaction_ids'],
  title: 'BatchTransactionTagsRequest',
  description: 'Request body for batch fetching transaction tags.',
} as const

export const $Body_card_statements_upload_statement = {
  properties: {
    card_id: {
      type: 'string',
      format: 'uuid',
      title: 'Card Id',
    },
    file: {
      type: 'string',
      format: 'binary',
      title: 'File',
    },
  },
  type: 'object',
  required: ['card_id', 'file'],
  title: 'Body_card-statements-upload_statement',
} as const

export const $Body_login_login_access_token = {
  properties: {
    grant_type: {
      anyOf: [
        {
          type: 'string',
          pattern: '^password$',
        },
        {
          type: 'null',
        },
      ],
      title: 'Grant Type',
    },
    username: {
      type: 'string',
      title: 'Username',
    },
    password: {
      type: 'string',
      format: 'password',
      title: 'Password',
    },
    scope: {
      type: 'string',
      title: 'Scope',
      default: '',
    },
    client_id: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Client Id',
    },
    client_secret: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      format: 'password',
      title: 'Client Secret',
    },
  },
  type: 'object',
  required: ['username', 'password'],
  title: 'Body_login-login_access_token',
} as const

export const $CardBrand = {
  type: 'string',
  enum: ['visa', 'mastercard', 'amex', 'discover', 'other'],
  title: 'CardBrand',
  description: 'Enumeration for credit card brands.',
} as const

export const $CardStatementCreate = {
  properties: {
    card_id: {
      type: 'string',
      format: 'uuid',
      title: 'Card Id',
    },
    period_start: {
      anyOf: [
        {
          type: 'string',
          format: 'date',
        },
        {
          type: 'null',
        },
      ],
      title: 'Period Start',
    },
    period_end: {
      anyOf: [
        {
          type: 'string',
          format: 'date',
        },
        {
          type: 'null',
        },
      ],
      title: 'Period End',
    },
    close_date: {
      anyOf: [
        {
          type: 'string',
          format: 'date',
        },
        {
          type: 'null',
        },
      ],
      title: 'Close Date',
    },
    due_date: {
      anyOf: [
        {
          type: 'string',
          format: 'date',
        },
        {
          type: 'null',
        },
      ],
      title: 'Due Date',
    },
    previous_balance: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'string',
          pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
        },
        {
          type: 'null',
        },
      ],
      title: 'Previous Balance',
    },
    current_balance: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'string',
          pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Balance',
    },
    minimum_payment: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'string',
          pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
        },
        {
          type: 'null',
        },
      ],
      title: 'Minimum Payment',
    },
    is_fully_paid: {
      type: 'boolean',
      title: 'Is Fully Paid',
      default: false,
    },
    currency: {
      type: 'string',
      maxLength: 3,
      title: 'Currency',
      default: 'ARS',
    },
    status: {
      $ref: '#/components/schemas/StatementStatus',
      default: 'complete',
    },
    source_file_path: {
      anyOf: [
        {
          type: 'string',
          maxLength: 500,
        },
        {
          type: 'null',
        },
      ],
      title: 'Source File Path',
    },
  },
  type: 'object',
  required: ['card_id'],
  title: 'CardStatementCreate',
  description: 'Model for creating card statement.',
} as const

export const $CardStatementPublic = {
  properties: {
    card_id: {
      type: 'string',
      format: 'uuid',
      title: 'Card Id',
    },
    period_start: {
      anyOf: [
        {
          type: 'string',
          format: 'date',
        },
        {
          type: 'null',
        },
      ],
      title: 'Period Start',
    },
    period_end: {
      anyOf: [
        {
          type: 'string',
          format: 'date',
        },
        {
          type: 'null',
        },
      ],
      title: 'Period End',
    },
    close_date: {
      anyOf: [
        {
          type: 'string',
          format: 'date',
        },
        {
          type: 'null',
        },
      ],
      title: 'Close Date',
    },
    due_date: {
      anyOf: [
        {
          type: 'string',
          format: 'date',
        },
        {
          type: 'null',
        },
      ],
      title: 'Due Date',
    },
    previous_balance: {
      anyOf: [
        {
          type: 'string',
          pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
        },
        {
          type: 'null',
        },
      ],
      title: 'Previous Balance',
    },
    current_balance: {
      anyOf: [
        {
          type: 'string',
          pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Balance',
    },
    minimum_payment: {
      anyOf: [
        {
          type: 'string',
          pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
        },
        {
          type: 'null',
        },
      ],
      title: 'Minimum Payment',
    },
    is_fully_paid: {
      type: 'boolean',
      title: 'Is Fully Paid',
      default: false,
    },
    currency: {
      type: 'string',
      maxLength: 3,
      title: 'Currency',
      default: 'ARS',
    },
    status: {
      $ref: '#/components/schemas/StatementStatus',
      default: 'complete',
    },
    source_file_path: {
      anyOf: [
        {
          type: 'string',
          maxLength: 500,
        },
        {
          type: 'null',
        },
      ],
      title: 'Source File Path',
    },
    id: {
      type: 'string',
      format: 'uuid',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['card_id', 'id'],
  title: 'CardStatementPublic',
  description: 'Public model for card statements.',
} as const

export const $CardStatementUpdate = {
  properties: {
    card_id: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid',
        },
        {
          type: 'null',
        },
      ],
      title: 'Card Id',
    },
    period_start: {
      anyOf: [
        {
          type: 'string',
          format: 'date',
        },
        {
          type: 'null',
        },
      ],
      title: 'Period Start',
    },
    period_end: {
      anyOf: [
        {
          type: 'string',
          format: 'date',
        },
        {
          type: 'null',
        },
      ],
      title: 'Period End',
    },
    close_date: {
      anyOf: [
        {
          type: 'string',
          format: 'date',
        },
        {
          type: 'null',
        },
      ],
      title: 'Close Date',
    },
    due_date: {
      anyOf: [
        {
          type: 'string',
          format: 'date',
        },
        {
          type: 'null',
        },
      ],
      title: 'Due Date',
    },
    previous_balance: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'string',
          pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
        },
        {
          type: 'null',
        },
      ],
      title: 'Previous Balance',
    },
    current_balance: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'string',
          pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
        },
        {
          type: 'null',
        },
      ],
      title: 'Current Balance',
    },
    minimum_payment: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'string',
          pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
        },
        {
          type: 'null',
        },
      ],
      title: 'Minimum Payment',
    },
    is_fully_paid: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Is Fully Paid',
    },
    currency: {
      anyOf: [
        {
          type: 'string',
          maxLength: 3,
        },
        {
          type: 'null',
        },
      ],
      title: 'Currency',
    },
    status: {
      anyOf: [
        {
          $ref: '#/components/schemas/StatementStatus',
        },
        {
          type: 'null',
        },
      ],
    },
    source_file_path: {
      anyOf: [
        {
          type: 'string',
          maxLength: 500,
        },
        {
          type: 'null',
        },
      ],
      title: 'Source File Path',
    },
  },
  type: 'object',
  title: 'CardStatementUpdate',
  description: 'Model for updating card statement.',
} as const

export const $CardStatementsPublic = {
  properties: {
    data: {
      items: {
        $ref: '#/components/schemas/CardStatementPublic',
      },
      type: 'array',
      title: 'Data',
    },
    count: {
      type: 'integer',
      title: 'Count',
    },
    pagination: {
      anyOf: [
        {
          additionalProperties: {
            type: 'integer',
          },
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pagination',
    },
  },
  type: 'object',
  required: ['data', 'count'],
  title: 'CardStatementsPublic',
  description: 'Response model for paginated card statements.',
} as const

export const $ConditionField = {
  type: 'string',
  enum: ['payee', 'description', 'amount', 'date'],
  title: 'ConditionField',
  description: 'Fields that can be matched in rule conditions.',
} as const

export const $ConditionOperator = {
  type: 'string',
  enum: ['contains', 'equals', 'gt', 'gte', 'lt', 'lte', 'before', 'after', 'between'],
  title: 'ConditionOperator',
  description: 'Operators for condition matching.',
} as const

export const $CreditCardCreate = {
  properties: {
    user_id: {
      type: 'string',
      format: 'uuid',
      title: 'User Id',
    },
    bank: {
      type: 'string',
      maxLength: 100,
      title: 'Bank',
    },
    brand: {
      $ref: '#/components/schemas/CardBrand',
    },
    last4: {
      type: 'string',
      maxLength: 4,
      title: 'Last4',
    },
    alias: {
      anyOf: [
        {
          type: 'string',
          maxLength: 100,
        },
        {
          type: 'null',
        },
      ],
      title: 'Alias',
    },
    default_currency: {
      type: 'string',
      maxLength: 3,
      title: 'Default Currency',
      default: 'ARS',
    },
  },
  type: 'object',
  required: ['user_id', 'bank', 'brand', 'last4'],
  title: 'CreditCardCreate',
  description: 'Model for creating credit card.',
} as const

export const $CreditCardPublic = {
  properties: {
    user_id: {
      type: 'string',
      format: 'uuid',
      title: 'User Id',
    },
    bank: {
      type: 'string',
      maxLength: 100,
      title: 'Bank',
    },
    brand: {
      $ref: '#/components/schemas/CardBrand',
    },
    last4: {
      type: 'string',
      maxLength: 4,
      title: 'Last4',
    },
    alias: {
      anyOf: [
        {
          type: 'string',
          maxLength: 100,
        },
        {
          type: 'null',
        },
      ],
      title: 'Alias',
    },
    default_currency: {
      type: 'string',
      maxLength: 3,
      title: 'Default Currency',
      default: 'ARS',
    },
    id: {
      type: 'string',
      format: 'uuid',
      title: 'Id',
    },
    credit_limit: {
      anyOf: [
        {
          type: 'string',
          pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
        },
        {
          type: 'null',
        },
      ],
      title: 'Credit Limit',
    },
    limit_last_updated_at: {
      anyOf: [
        {
          type: 'string',
          format: 'date-time',
        },
        {
          type: 'null',
        },
      ],
      title: 'Limit Last Updated At',
    },
    limit_source: {
      anyOf: [
        {
          $ref: '#/components/schemas/LimitSource',
        },
        {
          type: 'null',
        },
      ],
    },
    outstanding_balance: {
      type: 'string',
      pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
      title: 'Outstanding Balance',
      default: '0',
    },
  },
  type: 'object',
  required: ['user_id', 'bank', 'brand', 'last4', 'id'],
  title: 'CreditCardPublic',
  description: 'Public model for credit cards.',
} as const

export const $CreditCardUpdate = {
  properties: {
    bank: {
      anyOf: [
        {
          type: 'string',
          maxLength: 100,
        },
        {
          type: 'null',
        },
      ],
      title: 'Bank',
    },
    brand: {
      anyOf: [
        {
          $ref: '#/components/schemas/CardBrand',
        },
        {
          type: 'null',
        },
      ],
    },
    last4: {
      anyOf: [
        {
          type: 'string',
          maxLength: 4,
        },
        {
          type: 'null',
        },
      ],
      title: 'Last4',
    },
    alias: {
      anyOf: [
        {
          type: 'string',
          maxLength: 100,
        },
        {
          type: 'null',
        },
      ],
      title: 'Alias',
    },
    default_currency: {
      anyOf: [
        {
          type: 'string',
          maxLength: 3,
        },
        {
          type: 'null',
        },
      ],
      title: 'Default Currency',
    },
    credit_limit: {
      anyOf: [
        {
          type: 'number',
          exclusiveMinimum: 0,
        },
        {
          type: 'string',
          pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
        },
        {
          type: 'null',
        },
      ],
      title: 'Credit Limit',
    },
  },
  type: 'object',
  title: 'CreditCardUpdate',
  description: 'Model for updating credit card.',
} as const

export const $CreditCardsPublic = {
  properties: {
    data: {
      items: {
        $ref: '#/components/schemas/CreditCardPublic',
      },
      type: 'array',
      title: 'Data',
    },
    count: {
      type: 'integer',
      title: 'Count',
    },
  },
  type: 'object',
  required: ['data', 'count'],
  title: 'CreditCardsPublic',
  description: 'Response model for paginated credit cards.',
} as const

export const $CurrencyConversionRequest = {
  properties: {
    amount: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'string',
          pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
        },
      ],
      title: 'Amount',
    },
    from_currency: {
      type: 'string',
      maxLength: 3,
      minLength: 3,
      title: 'From Currency',
    },
    to_currency: {
      type: 'string',
      maxLength: 3,
      minLength: 3,
      title: 'To Currency',
    },
    date: {
      anyOf: [
        {
          type: 'string',
          format: 'date',
        },
        {
          type: 'null',
        },
      ],
      title: 'Date',
    },
  },
  type: 'object',
  required: ['amount', 'from_currency', 'to_currency'],
  title: 'CurrencyConversionRequest',
  description: 'Request model for converting an amount from one currency to another.',
} as const

export const $CurrencyConversionResponse = {
  properties: {
    original_amount: {
      type: 'string',
      pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
      title: 'Original Amount',
    },
    converted_amount: {
      type: 'string',
      pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
      title: 'Converted Amount',
    },
    from_currency: {
      type: 'string',
      title: 'From Currency',
    },
    to_currency: {
      type: 'string',
      title: 'To Currency',
    },
    rate: {
      type: 'string',
      pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
      title: 'Rate',
    },
    rate_date: {
      type: 'string',
      format: 'date',
      title: 'Rate Date',
    },
  },
  type: 'object',
  required: [
    'original_amount',
    'converted_amount',
    'from_currency',
    'to_currency',
    'rate',
    'rate_date',
  ],
  title: 'CurrencyConversionResponse',
  description: 'Response model for a currency conversion.',
} as const

export const $ExchangeRatePublic = {
  properties: {
    rate_date: {
      type: 'string',
      format: 'date',
      title: 'Rate Date',
    },
    buy_rate: {
      type: 'string',
      pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
      title: 'Buy Rate',
    },
    sell_rate: {
      type: 'string',
      pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
      title: 'Sell Rate',
    },
    average_rate: {
      type: 'string',
      pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
      title: 'Average Rate',
    },
    source: {
      type: 'string',
      title: 'Source',
    },
    fetched_at: {
      type: 'string',
      format: 'date-time',
      title: 'Fetched At',
    },
  },
  type: 'object',
  required: ['rate_date', 'buy_rate', 'sell_rate', 'average_rate', 'source', 'fetched_at'],
  title: 'ExchangeRatePublic',
  description: 'Public response model for an exchange rate.',
} as const

export const $ExchangeRatesResponse = {
  properties: {
    base_currency: {
      type: 'string',
      title: 'Base Currency',
    },
    target_currency: {
      type: 'string',
      title: 'Target Currency',
    },
    rates: {
      items: {
        $ref: '#/components/schemas/ExchangeRatePublic',
      },
      type: 'array',
      title: 'Rates',
    },
  },
  type: 'object',
  required: ['base_currency', 'target_currency', 'rates'],
  title: 'ExchangeRatesResponse',
  description: 'Response model for multiple exchange rates.',
} as const

export const $HTTPValidationError = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError',
      },
      type: 'array',
      title: 'Detail',
    },
  },
  type: 'object',
  title: 'HTTPValidationError',
} as const

export const $LimitSource = {
  type: 'string',
  enum: ['manual', 'statement'],
  title: 'LimitSource',
  description: 'Enumeration for credit card limit sources.',
} as const

export const $LogicalOperator = {
  type: 'string',
  enum: ['AND', 'OR'],
  title: 'LogicalOperator',
  description: 'Logical operators for combining conditions.',
} as const

export const $Message = {
  properties: {
    message: {
      type: 'string',
      title: 'Message',
    },
  },
  type: 'object',
  required: ['message'],
  title: 'Message',
} as const

export const $NewPassword = {
  properties: {
    token: {
      type: 'string',
      title: 'Token',
    },
    new_password: {
      type: 'string',
      maxLength: 40,
      minLength: 8,
      title: 'New Password',
    },
  },
  type: 'object',
  required: ['token', 'new_password'],
  title: 'NewPassword',
} as const

export const $PaymentCreate = {
  properties: {
    user_id: {
      type: 'string',
      format: 'uuid',
      title: 'User Id',
    },
    statement_id: {
      type: 'string',
      format: 'uuid',
      title: 'Statement Id',
    },
    amount: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'string',
          pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
        },
      ],
      title: 'Amount',
    },
    payment_date: {
      type: 'string',
      format: 'date',
      title: 'Payment Date',
    },
    currency: {
      type: 'string',
      maxLength: 3,
      title: 'Currency',
    },
  },
  type: 'object',
  required: ['user_id', 'statement_id', 'amount', 'payment_date', 'currency'],
  title: 'PaymentCreate',
  description: 'Model for creating payment.',
} as const

export const $PaymentPublic = {
  properties: {
    user_id: {
      type: 'string',
      format: 'uuid',
      title: 'User Id',
    },
    statement_id: {
      type: 'string',
      format: 'uuid',
      title: 'Statement Id',
    },
    amount: {
      type: 'string',
      pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
      title: 'Amount',
    },
    payment_date: {
      type: 'string',
      format: 'date',
      title: 'Payment Date',
    },
    currency: {
      type: 'string',
      maxLength: 3,
      title: 'Currency',
    },
    id: {
      type: 'string',
      format: 'uuid',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['user_id', 'statement_id', 'amount', 'payment_date', 'currency', 'id'],
  title: 'PaymentPublic',
  description: 'Public model for payments.',
} as const

export const $PaymentUpdate = {
  properties: {
    statement_id: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid',
        },
        {
          type: 'null',
        },
      ],
      title: 'Statement Id',
    },
    amount: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'string',
          pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
        },
        {
          type: 'null',
        },
      ],
      title: 'Amount',
    },
    payment_date: {
      anyOf: [
        {
          type: 'string',
          format: 'date',
        },
        {
          type: 'null',
        },
      ],
      title: 'Payment Date',
    },
    currency: {
      anyOf: [
        {
          type: 'string',
          maxLength: 3,
        },
        {
          type: 'null',
        },
      ],
      title: 'Currency',
    },
  },
  type: 'object',
  title: 'PaymentUpdate',
  description: 'Model for updating payment.',
} as const

export const $PaymentsPublic = {
  properties: {
    data: {
      items: {
        $ref: '#/components/schemas/PaymentPublic',
      },
      type: 'array',
      title: 'Data',
    },
    count: {
      type: 'integer',
      title: 'Count',
    },
    pagination: {
      anyOf: [
        {
          additionalProperties: {
            type: 'integer',
          },
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pagination',
    },
  },
  type: 'object',
  required: ['data', 'count'],
  title: 'PaymentsPublic',
  description: 'Response model for paginated payments.',
} as const

export const $PrivateUserCreate = {
  properties: {
    email: {
      type: 'string',
      title: 'Email',
    },
    password: {
      type: 'string',
      title: 'Password',
    },
    full_name: {
      type: 'string',
      title: 'Full Name',
    },
    is_verified: {
      type: 'boolean',
      title: 'Is Verified',
      default: false,
    },
  },
  type: 'object',
  required: ['email', 'password', 'full_name'],
  title: 'PrivateUserCreate',
} as const

export const $RuleActionCreate = {
  properties: {
    action_type: {
      $ref: '#/components/schemas/ActionType',
    },
    tag_id: {
      type: 'string',
      format: 'uuid',
      title: 'Tag Id',
    },
  },
  type: 'object',
  required: ['action_type', 'tag_id'],
  title: 'RuleActionCreate',
  description: 'Input schema for creating an action within a rule.',
} as const

export const $RuleActionPublic = {
  properties: {
    action_id: {
      type: 'string',
      format: 'uuid',
      title: 'Action Id',
    },
    action_type: {
      $ref: '#/components/schemas/ActionType',
    },
    tag_id: {
      type: 'string',
      format: 'uuid',
      title: 'Tag Id',
    },
  },
  type: 'object',
  required: ['action_id', 'action_type', 'tag_id'],
  title: 'RuleActionPublic',
  description: 'Output schema for action in API responses.',
} as const

export const $RuleConditionCreate = {
  properties: {
    field: {
      $ref: '#/components/schemas/ConditionField',
    },
    operator: {
      $ref: '#/components/schemas/ConditionOperator',
    },
    value: {
      type: 'string',
      title: 'Value',
    },
    value_secondary: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Value Secondary',
    },
    logical_operator: {
      $ref: '#/components/schemas/LogicalOperator',
      default: 'AND',
    },
  },
  type: 'object',
  required: ['field', 'operator', 'value'],
  title: 'RuleConditionCreate',
  description: 'Input schema for creating a condition within a rule.',
} as const

export const $RuleConditionPublic = {
  properties: {
    condition_id: {
      type: 'string',
      format: 'uuid',
      title: 'Condition Id',
    },
    field: {
      $ref: '#/components/schemas/ConditionField',
    },
    operator: {
      $ref: '#/components/schemas/ConditionOperator',
    },
    value: {
      type: 'string',
      title: 'Value',
    },
    value_secondary: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Value Secondary',
    },
    logical_operator: {
      $ref: '#/components/schemas/LogicalOperator',
    },
    position: {
      type: 'integer',
      title: 'Position',
    },
  },
  type: 'object',
  required: [
    'condition_id',
    'field',
    'operator',
    'value',
    'value_secondary',
    'logical_operator',
    'position',
  ],
  title: 'RuleConditionPublic',
  description: 'Output schema for condition in API responses.',
} as const

export const $RuleCreate = {
  properties: {
    name: {
      type: 'string',
      maxLength: 200,
      title: 'Name',
    },
    is_active: {
      type: 'boolean',
      title: 'Is Active',
      default: true,
    },
    conditions: {
      items: {
        $ref: '#/components/schemas/RuleConditionCreate',
      },
      type: 'array',
      title: 'Conditions',
    },
    actions: {
      items: {
        $ref: '#/components/schemas/RuleActionCreate',
      },
      type: 'array',
      title: 'Actions',
    },
  },
  type: 'object',
  required: ['name', 'conditions', 'actions'],
  title: 'RuleCreate',
  description: 'Input schema for creating a complete rule with conditions and actions.',
} as const

export const $RuleMatch = {
  properties: {
    rule_id: {
      type: 'string',
      format: 'uuid',
      title: 'Rule Id',
    },
    rule_name: {
      type: 'string',
      title: 'Rule Name',
    },
    tags_applied: {
      items: {
        type: 'string',
        format: 'uuid',
      },
      type: 'array',
      title: 'Tags Applied',
    },
  },
  type: 'object',
  required: ['rule_id', 'rule_name', 'tags_applied'],
  title: 'RuleMatch',
  description: 'Info about a single rule that matched a transaction.',
} as const

export const $RulePublic = {
  properties: {
    name: {
      type: 'string',
      maxLength: 200,
      title: 'Name',
    },
    is_active: {
      type: 'boolean',
      title: 'Is Active',
      default: true,
    },
    rule_id: {
      type: 'string',
      format: 'uuid',
      title: 'Rule Id',
    },
    user_id: {
      type: 'string',
      format: 'uuid',
      title: 'User Id',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
    },
    updated_at: {
      anyOf: [
        {
          type: 'string',
          format: 'date-time',
        },
        {
          type: 'null',
        },
      ],
      title: 'Updated At',
    },
    conditions: {
      items: {
        $ref: '#/components/schemas/RuleConditionPublic',
      },
      type: 'array',
      title: 'Conditions',
    },
    actions: {
      items: {
        $ref: '#/components/schemas/RuleActionPublic',
      },
      type: 'array',
      title: 'Actions',
    },
  },
  type: 'object',
  required: ['name', 'rule_id', 'user_id', 'created_at', 'updated_at', 'conditions', 'actions'],
  title: 'RulePublic',
  description: 'Output schema for complete rule in API responses.',
} as const

export const $RuleUpdate = {
  properties: {
    name: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Name',
    },
    is_active: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Is Active',
    },
    conditions: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/RuleConditionCreate',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Conditions',
    },
    actions: {
      anyOf: [
        {
          items: {
            $ref: '#/components/schemas/RuleActionCreate',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Actions',
    },
  },
  type: 'object',
  title: 'RuleUpdate',
  description: 'Input schema for partial rule updates.',
} as const

export const $RulesPublic = {
  properties: {
    data: {
      items: {
        $ref: '#/components/schemas/RulePublic',
      },
      type: 'array',
      title: 'Data',
    },
    count: {
      type: 'integer',
      title: 'Count',
    },
  },
  type: 'object',
  required: ['data', 'count'],
  title: 'RulesPublic',
  description: 'Paginated list response for rules.',
} as const

export const $StatementStatus = {
  type: 'string',
  enum: ['complete', 'pending_review'],
  title: 'StatementStatus',
  description: 'Status of a card statement.',
} as const

export const $TagCreate = {
  properties: {
    user_id: {
      type: 'string',
      format: 'uuid',
      title: 'User Id',
    },
    label: {
      type: 'string',
      maxLength: 200,
      title: 'Label',
    },
    color: {
      anyOf: [
        {
          type: 'string',
          maxLength: 7,
        },
        {
          type: 'null',
        },
      ],
      title: 'Color',
    },
  },
  type: 'object',
  required: ['user_id', 'label'],
  title: 'TagCreate',
  description: 'Model for creating tag.',
} as const

export const $TagPublic = {
  properties: {
    user_id: {
      type: 'string',
      format: 'uuid',
      title: 'User Id',
    },
    label: {
      type: 'string',
      maxLength: 200,
      title: 'Label',
    },
    color: {
      anyOf: [
        {
          type: 'string',
          maxLength: 7,
        },
        {
          type: 'null',
        },
      ],
      title: 'Color',
    },
    tag_id: {
      type: 'string',
      format: 'uuid',
      title: 'Tag Id',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
    },
  },
  type: 'object',
  required: ['user_id', 'label', 'tag_id', 'created_at'],
  title: 'TagPublic',
  description: 'Public model for tags.',
} as const

export const $TagUpdate = {
  properties: {
    label: {
      anyOf: [
        {
          type: 'string',
          maxLength: 200,
        },
        {
          type: 'null',
        },
      ],
      title: 'Label',
    },
    color: {
      anyOf: [
        {
          type: 'string',
          maxLength: 7,
        },
        {
          type: 'null',
        },
      ],
      title: 'Color',
    },
  },
  type: 'object',
  title: 'TagUpdate',
  description: 'Model for updating tag.',
} as const

export const $TagsPublic = {
  properties: {
    data: {
      items: {
        $ref: '#/components/schemas/TagPublic',
      },
      type: 'array',
      title: 'Data',
    },
    count: {
      type: 'integer',
      title: 'Count',
    },
    pagination: {
      anyOf: [
        {
          additionalProperties: {
            type: 'integer',
          },
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pagination',
    },
  },
  type: 'object',
  required: ['data', 'count'],
  title: 'TagsPublic',
  description: 'Response model for paginated tags.',
} as const

export const $Token = {
  properties: {
    access_token: {
      type: 'string',
      title: 'Access Token',
    },
    token_type: {
      type: 'string',
      title: 'Token Type',
      default: 'bearer',
    },
  },
  type: 'object',
  required: ['access_token'],
  title: 'Token',
} as const

export const $TransactionCreate = {
  properties: {
    statement_id: {
      type: 'string',
      format: 'uuid',
      title: 'Statement Id',
    },
    txn_date: {
      type: 'string',
      format: 'date',
      title: 'Txn Date',
    },
    payee: {
      type: 'string',
      maxLength: 200,
      title: 'Payee',
    },
    description: {
      type: 'string',
      maxLength: 500,
      title: 'Description',
    },
    amount: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'string',
          pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
        },
      ],
      title: 'Amount',
    },
    currency: {
      type: 'string',
      maxLength: 3,
      title: 'Currency',
    },
    coupon: {
      anyOf: [
        {
          type: 'string',
          maxLength: 200,
        },
        {
          type: 'null',
        },
      ],
      title: 'Coupon',
    },
    installment_cur: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Installment Cur',
    },
    installment_tot: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Installment Tot',
    },
  },
  type: 'object',
  required: ['statement_id', 'txn_date', 'payee', 'description', 'amount', 'currency'],
  title: 'TransactionCreate',
  description: 'Model for creating transaction.',
} as const

export const $TransactionMatch = {
  properties: {
    transaction_id: {
      type: 'string',
      format: 'uuid',
      title: 'Transaction Id',
    },
    matched_rules: {
      items: {
        $ref: '#/components/schemas/RuleMatch',
      },
      type: 'array',
      title: 'Matched Rules',
    },
  },
  type: 'object',
  required: ['transaction_id', 'matched_rules'],
  title: 'TransactionMatch',
  description: 'Info about a transaction and which rules matched it.',
} as const

export const $TransactionPublic = {
  properties: {
    statement_id: {
      type: 'string',
      format: 'uuid',
      title: 'Statement Id',
    },
    txn_date: {
      type: 'string',
      format: 'date',
      title: 'Txn Date',
    },
    payee: {
      type: 'string',
      maxLength: 200,
      title: 'Payee',
    },
    description: {
      type: 'string',
      maxLength: 500,
      title: 'Description',
    },
    amount: {
      type: 'string',
      pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
      title: 'Amount',
    },
    currency: {
      type: 'string',
      maxLength: 3,
      title: 'Currency',
    },
    coupon: {
      anyOf: [
        {
          type: 'string',
          maxLength: 200,
        },
        {
          type: 'null',
        },
      ],
      title: 'Coupon',
    },
    installment_cur: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Installment Cur',
    },
    installment_tot: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Installment Tot',
    },
    id: {
      type: 'string',
      format: 'uuid',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['statement_id', 'txn_date', 'payee', 'description', 'amount', 'currency', 'id'],
  title: 'TransactionPublic',
  description: 'Public model for transactions.',
} as const

export const $TransactionTagCreate = {
  properties: {
    transaction_id: {
      type: 'string',
      format: 'uuid',
      title: 'Transaction Id',
    },
    tag_id: {
      type: 'string',
      format: 'uuid',
      title: 'Tag Id',
    },
  },
  type: 'object',
  required: ['transaction_id', 'tag_id'],
  title: 'TransactionTagCreate',
  description: 'Model for creating a transaction tag relationship.',
} as const

export const $TransactionTagPublic = {
  properties: {
    transaction_id: {
      type: 'string',
      format: 'uuid',
      title: 'Transaction Id',
    },
    tag_id: {
      type: 'string',
      format: 'uuid',
      title: 'Tag Id',
    },
  },
  type: 'object',
  required: ['transaction_id', 'tag_id'],
  title: 'TransactionTagPublic',
  description: 'Public model for transaction tags.',
} as const

export const $TransactionUpdate = {
  properties: {
    txn_date: {
      anyOf: [
        {
          type: 'string',
          format: 'date',
        },
        {
          type: 'null',
        },
      ],
      title: 'Txn Date',
    },
    payee: {
      anyOf: [
        {
          type: 'string',
          maxLength: 200,
        },
        {
          type: 'null',
        },
      ],
      title: 'Payee',
    },
    description: {
      anyOf: [
        {
          type: 'string',
          maxLength: 500,
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
    amount: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'string',
          pattern: '^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$',
        },
        {
          type: 'null',
        },
      ],
      title: 'Amount',
    },
    currency: {
      anyOf: [
        {
          type: 'string',
          maxLength: 3,
        },
        {
          type: 'null',
        },
      ],
      title: 'Currency',
    },
    coupon: {
      anyOf: [
        {
          type: 'string',
          maxLength: 200,
        },
        {
          type: 'null',
        },
      ],
      title: 'Coupon',
    },
    installment_cur: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Installment Cur',
    },
    installment_tot: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Installment Tot',
    },
  },
  type: 'object',
  title: 'TransactionUpdate',
  description: 'Model for updating transaction.',
} as const

export const $TransactionsPublic = {
  properties: {
    data: {
      items: {
        $ref: '#/components/schemas/TransactionPublic',
      },
      type: 'array',
      title: 'Data',
    },
    count: {
      type: 'integer',
      title: 'Count',
    },
    pagination: {
      anyOf: [
        {
          additionalProperties: {
            type: 'integer',
          },
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Pagination',
    },
  },
  type: 'object',
  required: ['data', 'count'],
  title: 'TransactionsPublic',
  description: 'Response model for paginated transactions.',
} as const

export const $TriggerResponse = {
  properties: {
    statements_found: {
      type: 'integer',
      title: 'Statements Found',
    },
    notification_sent: {
      type: 'boolean',
      title: 'Notification Sent',
    },
  },
  type: 'object',
  required: ['statements_found', 'notification_sent'],
  title: 'TriggerResponse',
} as const

export const $UpdatePassword = {
  properties: {
    current_password: {
      type: 'string',
      maxLength: 40,
      minLength: 8,
      title: 'Current Password',
    },
    new_password: {
      type: 'string',
      maxLength: 40,
      minLength: 8,
      title: 'New Password',
    },
  },
  type: 'object',
  required: ['current_password', 'new_password'],
  title: 'UpdatePassword',
} as const

export const $UploadJobPublic = {
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
      title: 'Id',
    },
    status: {
      $ref: '#/components/schemas/UploadJobStatus',
    },
    statement_id: {
      anyOf: [
        {
          type: 'string',
          format: 'uuid',
        },
        {
          type: 'null',
        },
      ],
      title: 'Statement Id',
    },
    error_message: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Error Message',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
    },
    updated_at: {
      anyOf: [
        {
          type: 'string',
          format: 'date-time',
        },
        {
          type: 'null',
        },
      ],
      title: 'Updated At',
    },
    completed_at: {
      anyOf: [
        {
          type: 'string',
          format: 'date-time',
        },
        {
          type: 'null',
        },
      ],
      title: 'Completed At',
    },
  },
  type: 'object',
  required: [
    'id',
    'status',
    'statement_id',
    'error_message',
    'created_at',
    'updated_at',
    'completed_at',
  ],
  title: 'UploadJobPublic',
  description: 'Public model for upload jobs.',
} as const

export const $UploadJobStatus = {
  type: 'string',
  enum: ['pending', 'processing', 'completed', 'failed', 'partial'],
  title: 'UploadJobStatus',
  description: 'Status of an upload job.',
} as const

export const $UserBalancePublic = {
  properties: {
    total_balance: {
      type: 'number',
      title: 'Total Balance',
    },
    monthly_balance: {
      type: 'number',
      title: 'Monthly Balance',
    },
  },
  type: 'object',
  required: ['total_balance', 'monthly_balance'],
  title: 'UserBalancePublic',
  description: 'Response model for user balance information.',
} as const

export const $UserCreate = {
  properties: {
    email: {
      type: 'string',
      maxLength: 255,
      format: 'email',
      title: 'Email',
    },
    is_active: {
      type: 'boolean',
      title: 'Is Active',
      default: true,
    },
    is_superuser: {
      type: 'boolean',
      title: 'Is Superuser',
      default: false,
    },
    full_name: {
      anyOf: [
        {
          type: 'string',
          maxLength: 255,
        },
        {
          type: 'null',
        },
      ],
      title: 'Full Name',
    },
    preferred_currency: {
      anyOf: [
        {
          type: 'string',
          maxLength: 3,
        },
        {
          type: 'null',
        },
      ],
      title: 'Preferred Currency',
    },
    notifications_enabled: {
      type: 'boolean',
      title: 'Notifications Enabled',
      default: false,
    },
    ntfy_topic: {
      anyOf: [
        {
          type: 'string',
          maxLength: 100,
        },
        {
          type: 'null',
        },
      ],
      title: 'Ntfy Topic',
    },
    password: {
      type: 'string',
      maxLength: 40,
      minLength: 8,
      title: 'Password',
    },
  },
  type: 'object',
  required: ['email', 'password'],
  title: 'UserCreate',
} as const

export const $UserPublic = {
  properties: {
    email: {
      type: 'string',
      maxLength: 255,
      format: 'email',
      title: 'Email',
    },
    is_active: {
      type: 'boolean',
      title: 'Is Active',
      default: true,
    },
    is_superuser: {
      type: 'boolean',
      title: 'Is Superuser',
      default: false,
    },
    full_name: {
      anyOf: [
        {
          type: 'string',
          maxLength: 255,
        },
        {
          type: 'null',
        },
      ],
      title: 'Full Name',
    },
    preferred_currency: {
      anyOf: [
        {
          type: 'string',
          maxLength: 3,
        },
        {
          type: 'null',
        },
      ],
      title: 'Preferred Currency',
    },
    notifications_enabled: {
      type: 'boolean',
      title: 'Notifications Enabled',
      default: false,
    },
    ntfy_topic: {
      anyOf: [
        {
          type: 'string',
          maxLength: 100,
        },
        {
          type: 'null',
        },
      ],
      title: 'Ntfy Topic',
    },
    id: {
      type: 'string',
      format: 'uuid',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['email', 'id'],
  title: 'UserPublic',
} as const

export const $UserRegister = {
  properties: {
    email: {
      type: 'string',
      maxLength: 255,
      format: 'email',
      title: 'Email',
    },
    password: {
      type: 'string',
      maxLength: 40,
      minLength: 8,
      title: 'Password',
    },
    full_name: {
      anyOf: [
        {
          type: 'string',
          maxLength: 255,
        },
        {
          type: 'null',
        },
      ],
      title: 'Full Name',
    },
  },
  type: 'object',
  required: ['email', 'password'],
  title: 'UserRegister',
} as const

export const $UserUpdate = {
  properties: {
    email: {
      anyOf: [
        {
          type: 'string',
          maxLength: 255,
          format: 'email',
        },
        {
          type: 'null',
        },
      ],
      title: 'Email',
    },
    is_active: {
      type: 'boolean',
      title: 'Is Active',
      default: true,
    },
    is_superuser: {
      type: 'boolean',
      title: 'Is Superuser',
      default: false,
    },
    full_name: {
      anyOf: [
        {
          type: 'string',
          maxLength: 255,
        },
        {
          type: 'null',
        },
      ],
      title: 'Full Name',
    },
    preferred_currency: {
      anyOf: [
        {
          type: 'string',
          maxLength: 3,
        },
        {
          type: 'null',
        },
      ],
      title: 'Preferred Currency',
    },
    notifications_enabled: {
      type: 'boolean',
      title: 'Notifications Enabled',
      default: false,
    },
    ntfy_topic: {
      anyOf: [
        {
          type: 'string',
          maxLength: 100,
        },
        {
          type: 'null',
        },
      ],
      title: 'Ntfy Topic',
    },
    password: {
      anyOf: [
        {
          type: 'string',
          maxLength: 40,
          minLength: 8,
        },
        {
          type: 'null',
        },
      ],
      title: 'Password',
    },
  },
  type: 'object',
  title: 'UserUpdate',
} as const

export const $UserUpdateMe = {
  properties: {
    full_name: {
      anyOf: [
        {
          type: 'string',
          maxLength: 255,
        },
        {
          type: 'null',
        },
      ],
      title: 'Full Name',
    },
    email: {
      anyOf: [
        {
          type: 'string',
          maxLength: 255,
          format: 'email',
        },
        {
          type: 'null',
        },
      ],
      title: 'Email',
    },
    preferred_currency: {
      anyOf: [
        {
          type: 'string',
          maxLength: 3,
        },
        {
          type: 'null',
        },
      ],
      title: 'Preferred Currency',
    },
    notifications_enabled: {
      anyOf: [
        {
          type: 'boolean',
        },
        {
          type: 'null',
        },
      ],
      title: 'Notifications Enabled',
    },
    ntfy_topic: {
      anyOf: [
        {
          type: 'string',
          maxLength: 100,
        },
        {
          type: 'null',
        },
      ],
      title: 'Ntfy Topic',
    },
  },
  type: 'object',
  title: 'UserUpdateMe',
} as const

export const $UsersPublic = {
  properties: {
    data: {
      items: {
        $ref: '#/components/schemas/UserPublic',
      },
      type: 'array',
      title: 'Data',
    },
    count: {
      type: 'integer',
      title: 'Count',
    },
  },
  type: 'object',
  required: ['data', 'count'],
  title: 'UsersPublic',
} as const

export const $ValidationError = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string',
          },
          {
            type: 'integer',
          },
        ],
      },
      type: 'array',
      title: 'Location',
    },
    msg: {
      type: 'string',
      title: 'Message',
    },
    type: {
      type: 'string',
      title: 'Error Type',
    },
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError',
} as const
