// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise'
import { OpenAPI } from './core/OpenAPI'
import { request as __request } from './core/request'
import type { $OpenApiTs } from './types.gen'

export class LoginService {
  /**
   * Login Access Token
   * OAuth2 compatible token login, get an access token for future requests
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginLoginAccessToken(
    data: $OpenApiTs['/api/v1/login/access-token']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/login/access-token']['post']['res'][200]> {
    const { formData } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/login/access-token',
      formData,
      mediaType: 'application/x-www-form-urlencoded',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Test Token
   * Test access token
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static loginTestToken(): CancelablePromise<
    $OpenApiTs['/api/v1/login/test-token']['post']['res'][200]
  > {
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/login/test-token',
    })
  }

  /**
   * Recover Password
   * Password Recovery
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static loginRecoverPassword(
    data: $OpenApiTs['/api/v1/password-recovery/{email}']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/password-recovery/{email}']['post']['res'][200]> {
    const { email } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/password-recovery/{email}',
      path: {
        email,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Reset Password
   * Reset password
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static loginResetPassword(
    data: $OpenApiTs['/api/v1/reset-password/']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/reset-password/']['post']['res'][200]> {
    const { requestBody } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/reset-password/',
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Recover Password Html Content
   * HTML Content for Password Recovery
   * @returns string Successful Response
   * @throws ApiError
   */
  public static loginRecoverPasswordHtmlContent(
    data: $OpenApiTs['/api/v1/password-recovery-html-content/{email}']['post']['req'],
  ): CancelablePromise<
    $OpenApiTs['/api/v1/password-recovery-html-content/{email}']['post']['res'][200]
  > {
    const { email } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/password-recovery-html-content/{email}',
      path: {
        email,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }
}

export class UsersService {
  /**
   * List Users
   * List all users (superusers only).
   *
   * Args:
   * session: Database session
   * current_user: Current authenticated user
   * skip: Number of records to skip for pagination
   * limit: Maximum number of records to return
   *
   * Returns:
   * UsersPublic: Paginated list of users with total count
   *
   * Raises:
   * HTTPException: If user is not a superuser (403)
   * @returns UsersPublic Successful Response
   * @throws ApiError
   */
  public static usersListUsers(
    data: $OpenApiTs['/api/v1/users/']['get']['req'] = {},
  ): CancelablePromise<$OpenApiTs['/api/v1/users/']['get']['res'][200]> {
    const { skip, limit } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/users/',
      query: {
        skip,
        limit,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Create User
   * Create new user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static usersCreateUser(
    data: $OpenApiTs['/api/v1/users/']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/users/']['post']['res'][200]> {
    const { requestBody } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/users/',
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Get Current User
   * Get current user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static usersGetCurrentUser(): CancelablePromise<
    $OpenApiTs['/api/v1/users/me']['get']['res'][200]
  > {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/users/me',
    })
  }

  /**
   * Delete Current User
   * Delete own user.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static usersDeleteCurrentUser(): CancelablePromise<
    $OpenApiTs['/api/v1/users/me']['delete']['res'][200]
  > {
    return __request(OpenAPI, {
      method: 'DELETE',
      url: '/api/v1/users/me',
    })
  }

  /**
   * Update Current User
   * Update own user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static usersUpdateCurrentUser(
    data: $OpenApiTs['/api/v1/users/me']['patch']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/users/me']['patch']['res'][200]> {
    const { requestBody } = data
    return __request(OpenAPI, {
      method: 'PATCH',
      url: '/api/v1/users/me',
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Get User Balance
   * Get current user's balance information.
   *
   * Returns:
   * UserBalancePublic: Contains total_balance and monthly_balance
   *
   * Logic:
   * - Total balance: Sum of all transactions from unpaid/partially paid statements - all payments
   * - Monthly balance: Same as total, but excludes transactions with future installment dates
   * @returns UserBalancePublic Successful Response
   * @throws ApiError
   */
  public static usersGetUserBalance(): CancelablePromise<
    $OpenApiTs['/api/v1/users/me/balance']['get']['res'][200]
  > {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/users/me/balance',
    })
  }

  /**
   * Update Current User Password
   * Update own password.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static usersUpdateCurrentUserPassword(
    data: $OpenApiTs['/api/v1/users/me/password']['patch']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/users/me/password']['patch']['res'][200]> {
    const { requestBody } = data
    return __request(OpenAPI, {
      method: 'PATCH',
      url: '/api/v1/users/me/password',
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Register User
   * Create new user without the need to be logged in.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static usersRegisterUser(
    data: $OpenApiTs['/api/v1/users/signup']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/users/signup']['post']['res'][200]> {
    const { requestBody } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/users/signup',
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Get User By Id
   * Get a specific user by id.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static usersGetUserById(
    data: $OpenApiTs['/api/v1/users/{user_id}']['get']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/users/{user_id}']['get']['res'][200]> {
    const { userId } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/users/{user_id}',
      path: {
        user_id: userId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Update User By Id
   * Update a user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static usersUpdateUserById(
    data: $OpenApiTs['/api/v1/users/{user_id}']['patch']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/users/{user_id}']['patch']['res'][200]> {
    const { userId, requestBody } = data
    return __request(OpenAPI, {
      method: 'PATCH',
      url: '/api/v1/users/{user_id}',
      path: {
        user_id: userId,
      },
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Delete User By Id
   * Delete a user.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static usersDeleteUserById(
    data: $OpenApiTs['/api/v1/users/{user_id}']['delete']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/users/{user_id}']['delete']['res'][200]> {
    const { userId } = data
    return __request(OpenAPI, {
      method: 'DELETE',
      url: '/api/v1/users/{user_id}',
      path: {
        user_id: userId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }
}

export class CreditCardsService {
  /**
   * List Credit Cards
   * Retrieve credit cards.
   *
   * By default, returns the current user's cards. Superusers can filter by user_id.
   * @returns CreditCardsPublic Successful Response
   * @throws ApiError
   */
  public static creditCardsListCreditCards(
    data: $OpenApiTs['/api/v1/credit-cards/']['get']['req'] = {},
  ): CancelablePromise<$OpenApiTs['/api/v1/credit-cards/']['get']['res'][200]> {
    const { skip, limit, userId } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/credit-cards/',
      query: {
        skip,
        limit,
        user_id: userId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Create Credit Card
   * Create a new credit card.
   *
   * Users can only create cards for themselves.
   * Superusers can create cards for any user.
   * @returns CreditCardPublic Successful Response
   * @throws ApiError
   */
  public static creditCardsCreateCreditCard(
    data: $OpenApiTs['/api/v1/credit-cards/']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/credit-cards/']['post']['res'][201]> {
    const { requestBody } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/credit-cards/',
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Get Credit Card
   * Get a credit card by ID.
   *
   * Users can only get their own cards.
   * Superusers can get any card.
   * @returns CreditCardPublic Successful Response
   * @throws ApiError
   */
  public static creditCardsGetCreditCard(
    data: $OpenApiTs['/api/v1/credit-cards/{card_id}']['get']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/credit-cards/{card_id}']['get']['res'][200]> {
    const { cardId } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/credit-cards/{card_id}',
      path: {
        card_id: cardId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Update Credit Card
   * Update a credit card.
   *
   * Users can only update their own cards.
   * Superusers can update any card.
   * @returns CreditCardPublic Successful Response
   * @throws ApiError
   */
  public static creditCardsUpdateCreditCard(
    data: $OpenApiTs['/api/v1/credit-cards/{card_id}']['patch']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/credit-cards/{card_id}']['patch']['res'][200]> {
    const { cardId, requestBody } = data
    return __request(OpenAPI, {
      method: 'PATCH',
      url: '/api/v1/credit-cards/{card_id}',
      path: {
        card_id: cardId,
      },
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Delete Credit Card
   * Delete a credit card.
   *
   * Users can only delete their own cards.
   * Superusers can delete any card.
   * @returns void Successful Response
   * @throws ApiError
   */
  public static creditCardsDeleteCreditCard(
    data: $OpenApiTs['/api/v1/credit-cards/{card_id}']['delete']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/credit-cards/{card_id}']['delete']['res'][204]> {
    const { cardId } = data
    return __request(OpenAPI, {
      method: 'DELETE',
      url: '/api/v1/credit-cards/{card_id}',
      path: {
        card_id: cardId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }
}

export class CardStatementsService {
  /**
   * List Card Statements
   * Retrieve card statements.
   *
   * By default, returns the current user's statements. Superusers can filter by user_id.
   * Can also filter by card_id.
   * @returns CardStatementsPublic Successful Response
   * @throws ApiError
   */
  public static cardStatementsListCardStatements(
    data: $OpenApiTs['/api/v1/card-statements/']['get']['req'] = {},
  ): CancelablePromise<$OpenApiTs['/api/v1/card-statements/']['get']['res'][200]> {
    const { skip, limit, userId, cardId } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/card-statements/',
      query: {
        skip,
        limit,
        user_id: userId,
        card_id: cardId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Create Card Statement
   * Create a new card statement.
   *
   * Users can only create statements for cards they own.
   * Superusers can create statements for any card.
   * @returns CardStatementPublic Successful Response
   * @throws ApiError
   */
  public static cardStatementsCreateCardStatement(
    data: $OpenApiTs['/api/v1/card-statements/']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/card-statements/']['post']['res'][201]> {
    const { requestBody } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/card-statements/',
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Get Card Statement
   * Get a specific card statement by ID.
   *
   * Users can only view their own statements.
   * Superusers can view any statement.
   * @returns CardStatementPublic Successful Response
   * @throws ApiError
   */
  public static cardStatementsGetCardStatement(
    data: $OpenApiTs['/api/v1/card-statements/{statement_id}']['get']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/card-statements/{statement_id}']['get']['res'][200]> {
    const { statementId } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/card-statements/{statement_id}',
      path: {
        statement_id: statementId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Update Card Statement
   * Update a card statement.
   *
   * Users can only update their own statements.
   * Superusers can update any statement.
   * @returns CardStatementPublic Successful Response
   * @throws ApiError
   */
  public static cardStatementsUpdateCardStatement(
    data: $OpenApiTs['/api/v1/card-statements/{statement_id}']['patch']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/card-statements/{statement_id}']['patch']['res'][200]> {
    const { statementId, requestBody } = data
    return __request(OpenAPI, {
      method: 'PATCH',
      url: '/api/v1/card-statements/{statement_id}',
      path: {
        statement_id: statementId,
      },
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Delete Card Statement
   * Delete a card statement.
   *
   * Users can only delete their own statements.
   * Superusers can delete any statement.
   * @returns void Successful Response
   * @throws ApiError
   */
  public static cardStatementsDeleteCardStatement(
    data: $OpenApiTs['/api/v1/card-statements/{statement_id}']['delete']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/card-statements/{statement_id}']['delete']['res'][204]> {
    const { statementId } = data
    return __request(OpenAPI, {
      method: 'DELETE',
      url: '/api/v1/card-statements/{statement_id}',
      path: {
        statement_id: statementId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Upload a credit card statement PDF
   * Accepts a PDF file and starts async extraction. Returns job ID for status polling.
   * @returns UploadJobPublic Upload accepted, processing started
   * @throws ApiError
   */
  public static cardStatementsUploadStatement(
    data: $OpenApiTs['/api/v1/card-statements/upload']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/card-statements/upload']['post']['res'][202]> {
    const { formData } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/card-statements/upload',
      formData,
      mediaType: 'multipart/form-data',
      errors: {
        400: 'Invalid file (not PDF, too large, or duplicate)',
        403: "Card doesn't belong to user",
        404: 'Credit card not found',
        422: 'Validation Error',
      },
    })
  }
}

export class PaymentsService {
  /**
   * List Payments
   * Retrieve payments.
   *
   * By default, returns the current user's payments. Superusers can filter by user_id.
   * @returns PaymentsPublic Successful Response
   * @throws ApiError
   */
  public static paymentsListPayments(
    data: $OpenApiTs['/api/v1/payments/']['get']['req'] = {},
  ): CancelablePromise<$OpenApiTs['/api/v1/payments/']['get']['res'][200]> {
    const { skip, limit, userId } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/payments/',
      query: {
        skip,
        limit,
        user_id: userId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Create Payment
   * Create a new payment.
   *
   * Users can only create payments for themselves.
   * Superusers can create payments for any user.
   * @returns PaymentPublic Successful Response
   * @throws ApiError
   */
  public static paymentsCreatePayment(
    data: $OpenApiTs['/api/v1/payments/']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/payments/']['post']['res'][201]> {
    const { requestBody } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/payments/',
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Get Payment
   * Get a specific payment by ID.
   *
   * Users can only view their own payments.
   * Superusers can view any payment.
   * @returns PaymentPublic Successful Response
   * @throws ApiError
   */
  public static paymentsGetPayment(
    data: $OpenApiTs['/api/v1/payments/{payment_id}']['get']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/payments/{payment_id}']['get']['res'][200]> {
    const { paymentId } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/payments/{payment_id}',
      path: {
        payment_id: paymentId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Update Payment
   * Update a payment.
   *
   * Users can only update their own payments.
   * Superusers can update any payment.
   * @returns PaymentPublic Successful Response
   * @throws ApiError
   */
  public static paymentsUpdatePayment(
    data: $OpenApiTs['/api/v1/payments/{payment_id}']['patch']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/payments/{payment_id}']['patch']['res'][200]> {
    const { paymentId, requestBody } = data
    return __request(OpenAPI, {
      method: 'PATCH',
      url: '/api/v1/payments/{payment_id}',
      path: {
        payment_id: paymentId,
      },
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Delete Payment
   * Delete a payment.
   *
   * Users can only delete their own payments.
   * Superusers can delete any payment.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static paymentsDeletePayment(
    data: $OpenApiTs['/api/v1/payments/{payment_id}']['delete']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/payments/{payment_id}']['delete']['res'][200]> {
    const { paymentId } = data
    return __request(OpenAPI, {
      method: 'DELETE',
      url: '/api/v1/payments/{payment_id}',
      path: {
        payment_id: paymentId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }
}

export class TransactionsService {
  /**
   * List Transactions
   * Retrieve transactions.
   *
   * If statement_id is provided, returns transactions for that statement.
   * Users can only view transactions for statements they own (via credit card ownership).
   * Superusers can view transactions for any statement.
   * @returns TransactionsPublic Successful Response
   * @throws ApiError
   */
  public static transactionsListTransactions(
    data: $OpenApiTs['/api/v1/transactions/']['get']['req'] = {},
  ): CancelablePromise<$OpenApiTs['/api/v1/transactions/']['get']['res'][200]> {
    const { skip, limit, statementId } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/transactions/',
      query: {
        skip,
        limit,
        statement_id: statementId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Create Transaction
   * Create a new transaction.
   *
   * Users can only create transactions for statements they own.
   * Superusers can create transactions for any statement.
   * @returns TransactionPublic Successful Response
   * @throws ApiError
   */
  public static transactionsCreateTransaction(
    data: $OpenApiTs['/api/v1/transactions/']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/transactions/']['post']['res'][201]> {
    const { requestBody } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/transactions/',
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Get Transaction
   * Get a specific transaction by ID.
   *
   * Users can only view transactions for statements they own.
   * Superusers can view any transaction.
   * @returns TransactionPublic Successful Response
   * @throws ApiError
   */
  public static transactionsGetTransaction(
    data: $OpenApiTs['/api/v1/transactions/{transaction_id}']['get']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/transactions/{transaction_id}']['get']['res'][200]> {
    const { transactionId } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/transactions/{transaction_id}',
      path: {
        transaction_id: transactionId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Update Transaction
   * Update a transaction.
   *
   * Users can only update transactions for statements they own.
   * Superusers can update any transaction.
   * @returns TransactionPublic Successful Response
   * @throws ApiError
   */
  public static transactionsUpdateTransaction(
    data: $OpenApiTs['/api/v1/transactions/{transaction_id}']['patch']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/transactions/{transaction_id}']['patch']['res'][200]> {
    const { transactionId, requestBody } = data
    return __request(OpenAPI, {
      method: 'PATCH',
      url: '/api/v1/transactions/{transaction_id}',
      path: {
        transaction_id: transactionId,
      },
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Delete Transaction
   * Delete a transaction.
   *
   * Users can only delete transactions for statements they own.
   * Superusers can delete any transaction.
   * @returns void Successful Response
   * @throws ApiError
   */
  public static transactionsDeleteTransaction(
    data: $OpenApiTs['/api/v1/transactions/{transaction_id}']['delete']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/transactions/{transaction_id}']['delete']['res'][204]> {
    const { transactionId } = data
    return __request(OpenAPI, {
      method: 'DELETE',
      url: '/api/v1/transactions/{transaction_id}',
      path: {
        transaction_id: transactionId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }
}

export class CurrencyService {
  /**
   * Convert Currency
   * Convert a single amount between currencies.
   *
   * Uses database-backed exchange rates with fallback to closest date.
   *
   * Raises:
   * HTTPException(400): If the currency pair is not supported or date format is invalid.
   * HTTPException(404): If no exchange rate is found for the requested date (or fallback).
   * @returns CurrencyConversionResponse Successful Response
   * @throws ApiError
   */
  public static currencyConvertCurrency(
    data: $OpenApiTs['/api/v1/currency/convert']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/currency/convert']['post']['res'][200]> {
    const { requestBody, date } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/currency/convert',
      query: {
        date,
      },
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Convert Currency Batch
   * Convert multiple amounts between currencies.
   *
   * Uses database-backed exchange rates with fallback to closest date.
   *
   * Raises:
   * HTTPException(400): If any currency pair is not supported or date format is invalid.
   * HTTPException(404): If no exchange rate is found for the requested date (or fallback).
   * @returns BatchCurrencyConversionResponse Successful Response
   * @throws ApiError
   */
  public static currencyConvertCurrencyBatch(
    data: $OpenApiTs['/api/v1/currency/convert/batch']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/currency/convert/batch']['post']['res'][200]> {
    const { requestBody, date } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/currency/convert/batch',
      query: {
        date,
      },
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Trigger Extraction
   * Trigger manual extraction of the latest Dólar MEP rate (admin only).
   *
   * Enqueues a background job that:
   * 1. Fetches the current rate from Cronista
   * 2. Upserts it to the exchange_rate table
   * 3. Logs success or failure
   *
   * The endpoint returns immediately with 202 Accepted while the
   * extraction runs in the background.
   *
   * Returns:
   * {"status": "extraction_started"}
   *
   * Raises:
   * HTTPException(403): If user is not a superuser.
   * @returns string Successful Response
   * @throws ApiError
   */
  public static currencyTriggerExtraction(): CancelablePromise<
    $OpenApiTs['/api/v1/currency/rates/extract']['post']['res'][202]
  > {
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/currency/rates/extract',
    })
  }

  /**
   * Get Exchange Rates
   * Query exchange rates in three modes:
   *
   * - Latest: Default if no date params provided.
   * - Single date: If 'date' is provided (with closest-date fallback).
   * - Date range: If 'start_date' and 'end_date' are provided.
   *
   * Raises:
   * HTTPException(400): If currency params are invalid, unsupported, or if date params are conflicting/invalid.
   * @returns ExchangeRatesResponse Successful Response
   * @throws ApiError
   */
  public static currencyGetExchangeRates(
    data: $OpenApiTs['/api/v1/currency/rates']['get']['req'] = {},
  ): CancelablePromise<$OpenApiTs['/api/v1/currency/rates']['get']['res'][200]> {
    const { base, target, date, startDate, endDate } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/currency/rates',
      query: {
        base,
        target,
        date,
        start_date: startDate,
        end_date: endDate,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }
}

export class UploadJobsService {
  /**
   * Get upload job status
   * Poll this endpoint to check processing status. Returns statement_id when completed.
   * @returns UploadJobPublic Job found
   * @throws ApiError
   */
  public static uploadJobsGetUploadJob(
    data: $OpenApiTs['/api/v1/upload-jobs/{job_id}']['get']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/upload-jobs/{job_id}']['get']['res'][200]> {
    const { jobId } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/upload-jobs/{job_id}',
      path: {
        job_id: jobId,
      },
      errors: {
        404: 'Job not found or belongs to another user',
        422: 'Validation Error',
      },
    })
  }
}

export class TagsService {
  /**
   * List Tags
   * Retrieve tags.
   *
   * By default, returns the current user's tags. Superusers can filter by user_id.
   * @returns TagsPublic Successful Response
   * @throws ApiError
   */
  public static tagsListTags(
    data: $OpenApiTs['/api/v1/tags/']['get']['req'] = {},
  ): CancelablePromise<$OpenApiTs['/api/v1/tags/']['get']['res'][200]> {
    const { skip, limit, userId } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/tags/',
      query: {
        skip,
        limit,
        user_id: userId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Create Tag
   * Create a new tag.
   *
   * Users can only create tags for themselves.
   * Superusers can create tags for any user.
   * @returns TagPublic Successful Response
   * @throws ApiError
   */
  public static tagsCreateTag(
    data: $OpenApiTs['/api/v1/tags/']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/tags/']['post']['res'][201]> {
    const { requestBody } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/tags/',
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Get Tag
   * Get a specific tag by ID.
   *
   * Users can only view their own tags.
   * Superusers can view any tag.
   * @returns TagPublic Successful Response
   * @throws ApiError
   */
  public static tagsGetTag(
    data: $OpenApiTs['/api/v1/tags/{tag_id}']['get']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/tags/{tag_id}']['get']['res'][200]> {
    const { tagId } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/tags/{tag_id}',
      path: {
        tag_id: tagId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Update Tag
   * Update a tag.
   *
   * Users can only update their own tags.
   * Superusers can update any tag.
   * @returns TagPublic Successful Response
   * @throws ApiError
   */
  public static tagsUpdateTag(
    data: $OpenApiTs['/api/v1/tags/{tag_id}']['patch']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/tags/{tag_id}']['patch']['res'][200]> {
    const { tagId, requestBody } = data
    return __request(OpenAPI, {
      method: 'PATCH',
      url: '/api/v1/tags/{tag_id}',
      path: {
        tag_id: tagId,
      },
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Delete Tag
   * Delete a tag.
   *
   * Users can only delete their own tags.
   * Superusers can delete any tag.
   * @returns void Successful Response
   * @throws ApiError
   */
  public static tagsDeleteTag(
    data: $OpenApiTs['/api/v1/tags/{tag_id}']['delete']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/tags/{tag_id}']['delete']['res'][204]> {
    const { tagId } = data
    return __request(OpenAPI, {
      method: 'DELETE',
      url: '/api/v1/tags/{tag_id}',
      path: {
        tag_id: tagId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }
}

export class TransactionTagsService {
  /**
   * Add Tag To Transaction
   * Add a tag to a transaction.
   *
   * Users can only add tags to transactions they own.
   * Superusers can add tags to any transaction.
   * @returns TransactionTagPublic Successful Response
   * @throws ApiError
   */
  public static transactionTagsAddTagToTransaction(
    data: $OpenApiTs['/api/v1/transaction-tags/']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/transaction-tags/']['post']['res'][201]> {
    const { requestBody } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/transaction-tags/',
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Get Transaction Tags
   * Get all tags for a transaction.
   *
   * Users can only view tags for transactions they own (via credit card ownership).
   * Superusers can view tags for any transaction.
   * @returns TransactionTagPublic Successful Response
   * @throws ApiError
   */
  public static transactionTagsGetTransactionTags(
    data: $OpenApiTs['/api/v1/transaction-tags/transaction/{transaction_id}']['get']['req'],
  ): CancelablePromise<
    $OpenApiTs['/api/v1/transaction-tags/transaction/{transaction_id}']['get']['res'][200]
  > {
    const { transactionId } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/transaction-tags/transaction/{transaction_id}',
      path: {
        transaction_id: transactionId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Remove Tag From Transaction
   * Remove a tag from a transaction.
   *
   * Users can only remove tags from transactions they own.
   * Superusers can remove tags from any transaction.
   * @returns void Successful Response
   * @throws ApiError
   */
  public static transactionTagsRemoveTagFromTransaction(
    data: $OpenApiTs['/api/v1/transaction-tags/transaction/{transaction_id}/tag/{tag_id}']['delete']['req'],
  ): CancelablePromise<
    $OpenApiTs['/api/v1/transaction-tags/transaction/{transaction_id}/tag/{tag_id}']['delete']['res'][204]
  > {
    const { transactionId, tagId } = data
    return __request(OpenAPI, {
      method: 'DELETE',
      url: '/api/v1/transaction-tags/transaction/{transaction_id}/tag/{tag_id}',
      path: {
        transaction_id: transactionId,
        tag_id: tagId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }
}

export class RulesService {
  /**
   * Apply Rules
   * Apply rules to transactions.
   *
   * Evaluates all active rules for the current user against the specified
   * transactions. If a rule matches, its associated tags are applied.
   *
   * - If statement_id is provided, applies rules to all transactions in that statement
   * - If transaction_ids is provided, applies rules to those specific transactions
   * - If neither is provided, returns an empty response (no transactions to process)
   *
   * Returns details about which rules matched and which tags were applied.
   * @returns ApplyRulesResponse Successful Response
   * @throws ApiError
   */
  public static rulesApplyRules(
    data: $OpenApiTs['/api/v1/rules/apply']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/rules/apply']['post']['res'][200]> {
    const { requestBody } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/rules/apply',
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Create Rule
   * Create a new rule.
   *
   * Users can only create rules for themselves.
   * Superusers can create rules for any user.
   * @returns RulePublic Successful Response
   * @throws ApiError
   */
  public static rulesCreateRule(
    data: $OpenApiTs['/api/v1/rules/']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/rules/']['post']['res'][201]> {
    const { requestBody } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/rules/',
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * List Rules
   * Retrieve rules for the current user.
   *
   * Returns paginated list of rules belonging to the authenticated user.
   * @returns RulesPublic Successful Response
   * @throws ApiError
   */
  public static rulesListRules(
    data: $OpenApiTs['/api/v1/rules/']['get']['req'] = {},
  ): CancelablePromise<$OpenApiTs['/api/v1/rules/']['get']['res'][200]> {
    const { skip, limit } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/rules/',
      query: {
        skip,
        limit,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Get Rule
   * Get a specific rule by ID.
   *
   * Users can only view their own rules.
   * Superusers can view any rule.
   * @returns RulePublic Successful Response
   * @throws ApiError
   */
  public static rulesGetRule(
    data: $OpenApiTs['/api/v1/rules/{rule_id}']['get']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/rules/{rule_id}']['get']['res'][200]> {
    const { ruleId } = data
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/rules/{rule_id}',
      path: {
        rule_id: ruleId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Update Rule
   * Update a rule.
   *
   * Replaces the rule's conditions and actions with the provided data.
   * Users can only update their own rules.
   * Superusers can update any rule.
   * @returns RulePublic Successful Response
   * @throws ApiError
   */
  public static rulesUpdateRule(
    data: $OpenApiTs['/api/v1/rules/{rule_id}']['put']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/rules/{rule_id}']['put']['res'][200]> {
    const { ruleId, requestBody } = data
    return __request(OpenAPI, {
      method: 'PUT',
      url: '/api/v1/rules/{rule_id}',
      path: {
        rule_id: ruleId,
      },
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Delete Rule
   * Delete a rule.
   *
   * Cascades to delete all conditions and actions.
   * Users can only delete their own rules.
   * Superusers can delete any rule.
   * @returns void Successful Response
   * @throws ApiError
   */
  public static rulesDeleteRule(
    data: $OpenApiTs['/api/v1/rules/{rule_id}']['delete']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/rules/{rule_id}']['delete']['res'][204]> {
    const { ruleId } = data
    return __request(OpenAPI, {
      method: 'DELETE',
      url: '/api/v1/rules/{rule_id}',
      path: {
        rule_id: ruleId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }
}

export class UtilsService {
  /**
   * Test Email
   * Test emails.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static utilsTestEmail(
    data: $OpenApiTs['/api/v1/utils/test-email/']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/utils/test-email/']['post']['res'][201]> {
    const { emailTo } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/utils/test-email/',
      query: {
        email_to: emailTo,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Health Check
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static utilsHealthCheck(): CancelablePromise<
    $OpenApiTs['/api/v1/utils/health-check/']['get']['res'][200]
  > {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/v1/utils/health-check/',
    })
  }
}

export class PrivateService {
  /**
   * Create User
   * Create a new user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static privateCreateUser(
    data: $OpenApiTs['/api/v1/private/users/']['post']['req'],
  ): CancelablePromise<$OpenApiTs['/api/v1/private/users/']['post']['res'][200]> {
    const { requestBody } = data
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/v1/private/users/',
      body: requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }
}
