// This file is auto-generated by @hey-api/openapi-ts

/**
 * Types of actions a rule can perform.
 */
export type ActionType = 'add_tag'

/**
 * Input for the apply rules endpoint.
 */
export type ApplyRulesRequest = {
  statement_id?: string | null
  transaction_ids?: Array<string> | null
}

/**
 * Output for the apply rules endpoint.
 */
export type ApplyRulesResponse = {
  transactions_processed: number
  tags_applied: number
  details: Array<TransactionMatch>
}

/**
 * Request model for converting multiple amounts.
 */
export type BatchCurrencyConversionRequest = {
  conversions: Array<CurrencyConversionRequest>
}

/**
 * Response model for batch currency conversion.
 */
export type BatchCurrencyConversionResponse = {
  results: Array<CurrencyConversionResponse>
}

export type Body_card_statements_upload_statement = {
  card_id: string
  file: Blob | File
}

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

/**
 * Enumeration for credit card brands.
 */
export type CardBrand = 'visa' | 'mastercard' | 'amex' | 'discover' | 'other'

/**
 * Model for creating card statement.
 */
export type CardStatementCreate = {
  card_id: string
  period_start?: string | null
  period_end?: string | null
  close_date?: string | null
  due_date?: string | null
  previous_balance?: number | string | null
  current_balance?: number | string | null
  minimum_payment?: number | string | null
  is_fully_paid?: boolean
  currency?: string
  status?: StatementStatus
  source_file_path?: string | null
}

/**
 * Public model for card statements.
 */
export type CardStatementPublic = {
  card_id: string
  period_start?: string | null
  period_end?: string | null
  close_date?: string | null
  due_date?: string | null
  previous_balance?: string | null
  current_balance?: string | null
  minimum_payment?: string | null
  is_fully_paid?: boolean
  currency?: string
  status?: StatementStatus
  source_file_path?: string | null
  id: string
}

/**
 * Model for updating card statement.
 */
export type CardStatementUpdate = {
  card_id?: string | null
  period_start?: string | null
  period_end?: string | null
  close_date?: string | null
  due_date?: string | null
  previous_balance?: number | string | null
  current_balance?: number | string | null
  minimum_payment?: number | string | null
  is_fully_paid?: boolean | null
  currency?: string | null
  status?: StatementStatus | null
  source_file_path?: string | null
}

/**
 * Response model for paginated card statements.
 */
export type CardStatementsPublic = {
  data: Array<CardStatementPublic>
  count: number
  pagination?: {
    [key: string]: number
  } | null
}

/**
 * Fields that can be matched in rule conditions.
 */
export type ConditionField = 'payee' | 'description' | 'amount' | 'date'

/**
 * Operators for condition matching.
 */
export type ConditionOperator = 'contains' | 'equals' | 'gt' | 'gte' | 'lt' | 'lte' | 'before' | 'after' | 'between'

/**
 * Model for creating credit card.
 */
export type CreditCardCreate = {
  user_id: string
  bank: string
  brand: CardBrand
  last4: string
  alias?: string | null
  default_currency?: string
}

/**
 * Public model for credit cards.
 */
export type CreditCardPublic = {
  user_id: string
  bank: string
  brand: CardBrand
  last4: string
  alias?: string | null
  default_currency?: string
  id: string
}

/**
 * Model for updating credit card.
 */
export type CreditCardUpdate = {
  bank?: string | null
  brand?: CardBrand | null
  last4?: string | null
  alias?: string | null
  default_currency?: string | null
}

/**
 * Response model for paginated credit cards.
 */
export type CreditCardsPublic = {
  data: Array<CreditCardPublic>
  count: number
}

/**
 * Request model for converting an amount from one currency to another.
 */
export type CurrencyConversionRequest = {
  amount: number | string
  from_currency: string
  to_currency: string
  date?: string | null
}

/**
 * Response model for a currency conversion.
 */
export type CurrencyConversionResponse = {
  original_amount: string
  converted_amount: string
  from_currency: string
  to_currency: string
  rate: string
  rate_date: string
}

/**
 * Public response model for an exchange rate.
 */
export type ExchangeRatePublic = {
  rate_date: string
  buy_rate: string
  sell_rate: string
  average_rate: string
  source: string
  fetched_at: string
}

/**
 * Response model for multiple exchange rates.
 */
export type ExchangeRatesResponse = {
  base_currency: string
  target_currency: string
  rates: Array<ExchangeRatePublic>
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

/**
 * Logical operators for combining conditions.
 */
export type LogicalOperator = 'AND' | 'OR'

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

/**
 * Model for creating payment.
 */
export type PaymentCreate = {
  user_id: string
  statement_id: string
  amount: number | string
  payment_date: string
  currency: string
}

/**
 * Public model for payments.
 */
export type PaymentPublic = {
  user_id: string
  statement_id: string
  amount: string
  payment_date: string
  currency: string
  id: string
}

/**
 * Model for updating payment.
 */
export type PaymentUpdate = {
  statement_id?: string | null
  amount?: number | string | null
  payment_date?: string | null
  currency?: string | null
}

/**
 * Response model for paginated payments.
 */
export type PaymentsPublic = {
  data: Array<PaymentPublic>
  count: number
  pagination?: {
    [key: string]: number
  } | null
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

/**
 * Input schema for creating an action within a rule.
 */
export type RuleActionCreate = {
  action_type: ActionType
  tag_id: string
}

/**
 * Output schema for action in API responses.
 */
export type RuleActionPublic = {
  action_id: string
  action_type: ActionType
  tag_id: string
}

/**
 * Input schema for creating a condition within a rule.
 */
export type RuleConditionCreate = {
  field: ConditionField
  operator: ConditionOperator
  value: string
  value_secondary?: string | null
  logical_operator?: LogicalOperator
}

/**
 * Output schema for condition in API responses.
 */
export type RuleConditionPublic = {
  condition_id: string
  field: ConditionField
  operator: ConditionOperator
  value: string
  value_secondary: string | null
  logical_operator: LogicalOperator
  position: number
}

/**
 * Input schema for creating a complete rule with conditions and actions.
 */
export type RuleCreate = {
  name: string
  is_active?: boolean
  conditions: Array<RuleConditionCreate>
  actions: Array<RuleActionCreate>
}

/**
 * Info about a single rule that matched a transaction.
 */
export type RuleMatch = {
  rule_id: string
  rule_name: string
  tags_applied: Array<string>
}

/**
 * Output schema for complete rule in API responses.
 */
export type RulePublic = {
  name: string
  is_active?: boolean
  rule_id: string
  user_id: string
  created_at: string
  updated_at: string | null
  conditions: Array<RuleConditionPublic>
  actions: Array<RuleActionPublic>
}

/**
 * Input schema for partial rule updates.
 */
export type RuleUpdate = {
  name?: string | null
  is_active?: boolean | null
  conditions?: Array<RuleConditionCreate> | null
  actions?: Array<RuleActionCreate> | null
}

/**
 * Paginated list response for rules.
 */
export type RulesPublic = {
  data: Array<RulePublic>
  count: number
}

/**
 * Status of a card statement.
 */
export type StatementStatus = 'complete' | 'pending_review'

/**
 * Model for creating tag.
 */
export type TagCreate = {
  user_id: string
  label: string
  color?: string | null
}

/**
 * Public model for tags.
 */
export type TagPublic = {
  user_id: string
  label: string
  color?: string | null
  tag_id: string
  created_at: string
}

/**
 * Model for updating tag.
 */
export type TagUpdate = {
  label?: string | null
  color?: string | null
}

/**
 * Response model for paginated tags.
 */
export type TagsPublic = {
  data: Array<TagPublic>
  count: number
  pagination?: {
    [key: string]: number
  } | null
}

export type Token = {
  access_token: string
  token_type?: string
}

/**
 * Model for creating transaction.
 */
export type TransactionCreate = {
  statement_id: string
  txn_date: string
  payee: string
  description: string
  amount: number | string
  currency: string
  coupon?: string | null
  installment_cur?: number | null
  installment_tot?: number | null
}

/**
 * Info about a transaction and which rules matched it.
 */
export type TransactionMatch = {
  transaction_id: string
  matched_rules: Array<RuleMatch>
}

/**
 * Public model for transactions.
 */
export type TransactionPublic = {
  statement_id: string
  txn_date: string
  payee: string
  description: string
  amount: string
  currency: string
  coupon?: string | null
  installment_cur?: number | null
  installment_tot?: number | null
  id: string
}

/**
 * Model for creating a transaction tag relationship.
 */
export type TransactionTagCreate = {
  transaction_id: string
  tag_id: string
}

/**
 * Public model for transaction tags.
 */
export type TransactionTagPublic = {
  transaction_id: string
  tag_id: string
}

/**
 * Model for updating transaction.
 */
export type TransactionUpdate = {
  txn_date?: string | null
  payee?: string | null
  description?: string | null
  amount?: number | string | null
  currency?: string | null
  coupon?: string | null
  installment_cur?: number | null
  installment_tot?: number | null
}

/**
 * Response model for paginated transactions.
 */
export type TransactionsPublic = {
  data: Array<TransactionPublic>
  count: number
  pagination?: {
    [key: string]: number
  } | null
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

/**
 * Public model for upload jobs.
 */
export type UploadJobPublic = {
  id: string
  status: UploadJobStatus
  statement_id: string | null
  error_message: string | null
  created_at: string
  updated_at: string | null
  completed_at: string | null
}

/**
 * Status of an upload job.
 */
export type UploadJobStatus = 'pending' | 'processing' | 'completed' | 'failed' | 'partial'

/**
 * Response model for user balance information.
 */
export type UserBalancePublic = {
  total_balance: number
  monthly_balance: number
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  preferred_currency?: string | null
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  preferred_currency?: string | null
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  preferred_currency?: string | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
  preferred_currency?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type $OpenApiTs = {
  '/api/v1/login/access-token': {
    post: {
      req: {
        formData: Body_login_login_access_token
      }
      res: {
        /**
         * Successful Response
         */
        200: Token
      }
    }
  }
  '/api/v1/login/test-token': {
    post: {
      res: {
        /**
         * Successful Response
         */
        200: UserPublic
      }
    }
  }
  '/api/v1/password-recovery/{email}': {
    post: {
      req: {
        email: string
      }
      res: {
        /**
         * Successful Response
         */
        200: Message
      }
    }
  }
  '/api/v1/reset-password/': {
    post: {
      req: {
        requestBody: NewPassword
      }
      res: {
        /**
         * Successful Response
         */
        200: Message
      }
    }
  }
  '/api/v1/password-recovery-html-content/{email}': {
    post: {
      req: {
        email: string
      }
      res: {
        /**
         * Successful Response
         */
        200: string
      }
    }
  }
  '/api/v1/users/': {
    get: {
      req: {
        limit?: number
        skip?: number
      }
      res: {
        /**
         * Successful Response
         */
        200: UsersPublic
      }
    }
    post: {
      req: {
        requestBody: UserCreate
      }
      res: {
        /**
         * Successful Response
         */
        200: UserPublic
      }
    }
  }
  '/api/v1/users/me': {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: UserPublic
      }
    }
    delete: {
      res: {
        /**
         * Successful Response
         */
        200: Message
      }
    }
    patch: {
      req: {
        requestBody: UserUpdateMe
      }
      res: {
        /**
         * Successful Response
         */
        200: UserPublic
      }
    }
  }
  '/api/v1/users/me/balance': {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: UserBalancePublic
      }
    }
  }
  '/api/v1/users/me/password': {
    patch: {
      req: {
        requestBody: UpdatePassword
      }
      res: {
        /**
         * Successful Response
         */
        200: Message
      }
    }
  }
  '/api/v1/users/signup': {
    post: {
      req: {
        requestBody: UserRegister
      }
      res: {
        /**
         * Successful Response
         */
        200: UserPublic
      }
    }
  }
  '/api/v1/users/{user_id}': {
    get: {
      req: {
        userId: string
      }
      res: {
        /**
         * Successful Response
         */
        200: UserPublic
      }
    }
    patch: {
      req: {
        requestBody: UserUpdate
        userId: string
      }
      res: {
        /**
         * Successful Response
         */
        200: UserPublic
      }
    }
    delete: {
      req: {
        userId: string
      }
      res: {
        /**
         * Successful Response
         */
        200: Message
      }
    }
  }
  '/api/v1/credit-cards/': {
    get: {
      req: {
        limit?: number
        skip?: number
        userId?: string | null
      }
      res: {
        /**
         * Successful Response
         */
        200: CreditCardsPublic
      }
    }
    post: {
      req: {
        requestBody: CreditCardCreate
      }
      res: {
        /**
         * Successful Response
         */
        201: CreditCardPublic
      }
    }
  }
  '/api/v1/credit-cards/{card_id}': {
    get: {
      req: {
        cardId: string
      }
      res: {
        /**
         * Successful Response
         */
        200: CreditCardPublic
      }
    }
    patch: {
      req: {
        cardId: string
        requestBody: CreditCardUpdate
      }
      res: {
        /**
         * Successful Response
         */
        200: CreditCardPublic
      }
    }
    delete: {
      req: {
        cardId: string
      }
      res: {
        /**
         * Successful Response
         */
        204: void
      }
    }
  }
  '/api/v1/card-statements/': {
    get: {
      req: {
        cardId?: string | null
        limit?: number
        skip?: number
        userId?: string | null
      }
      res: {
        /**
         * Successful Response
         */
        200: CardStatementsPublic
      }
    }
    post: {
      req: {
        requestBody: CardStatementCreate
      }
      res: {
        /**
         * Successful Response
         */
        201: CardStatementPublic
      }
    }
  }
  '/api/v1/card-statements/{statement_id}': {
    get: {
      req: {
        statementId: string
      }
      res: {
        /**
         * Successful Response
         */
        200: CardStatementPublic
      }
    }
    patch: {
      req: {
        requestBody: CardStatementUpdate
        statementId: string
      }
      res: {
        /**
         * Successful Response
         */
        200: CardStatementPublic
      }
    }
    delete: {
      req: {
        statementId: string
      }
      res: {
        /**
         * Successful Response
         */
        204: void
      }
    }
  }
  '/api/v1/card-statements/upload': {
    post: {
      req: {
        formData: Body_card_statements_upload_statement
      }
      res: {
        /**
         * Upload accepted, processing started
         */
        202: UploadJobPublic
      }
    }
  }
  '/api/v1/payments/': {
    get: {
      req: {
        limit?: number
        skip?: number
        userId?: string | null
      }
      res: {
        /**
         * Successful Response
         */
        200: PaymentsPublic
      }
    }
    post: {
      req: {
        requestBody: PaymentCreate
      }
      res: {
        /**
         * Successful Response
         */
        201: PaymentPublic
      }
    }
  }
  '/api/v1/payments/{payment_id}': {
    get: {
      req: {
        paymentId: string
      }
      res: {
        /**
         * Successful Response
         */
        200: PaymentPublic
      }
    }
    patch: {
      req: {
        paymentId: string
        requestBody: PaymentUpdate
      }
      res: {
        /**
         * Successful Response
         */
        200: PaymentPublic
      }
    }
    delete: {
      req: {
        paymentId: string
      }
      res: {
        /**
         * Successful Response
         */
        200: Message
      }
    }
  }
  '/api/v1/transactions/': {
    get: {
      req: {
        limit?: number
        skip?: number
        statementId?: string | null
      }
      res: {
        /**
         * Successful Response
         */
        200: TransactionsPublic
      }
    }
    post: {
      req: {
        requestBody: TransactionCreate
      }
      res: {
        /**
         * Successful Response
         */
        201: TransactionPublic
      }
    }
  }
  '/api/v1/transactions/{transaction_id}': {
    get: {
      req: {
        transactionId: string
      }
      res: {
        /**
         * Successful Response
         */
        200: TransactionPublic
      }
    }
    patch: {
      req: {
        requestBody: TransactionUpdate
        transactionId: string
      }
      res: {
        /**
         * Successful Response
         */
        200: TransactionPublic
      }
    }
    delete: {
      req: {
        transactionId: string
      }
      res: {
        /**
         * Successful Response
         */
        204: void
      }
    }
  }
  '/api/v1/currency/convert': {
    post: {
      req: {
        /**
         * Optional date override (YYYY-MM-DD). Overrides date in request body if provided.
         */
        date?: string | null
        requestBody: CurrencyConversionRequest
      }
      res: {
        /**
         * Successful Response
         */
        200: CurrencyConversionResponse
      }
    }
  }
  '/api/v1/currency/convert/batch': {
    post: {
      req: {
        /**
         * Optional date override (YYYY-MM-DD). Overrides date in request body if provided for all conversions.
         */
        date?: string | null
        requestBody: BatchCurrencyConversionRequest
      }
      res: {
        /**
         * Successful Response
         */
        200: BatchCurrencyConversionResponse
      }
    }
  }
  '/api/v1/currency/rates/extract': {
    post: {
      res: {
        /**
         * Successful Response
         */
        202: {
          [key: string]: string
        }
      }
    }
  }
  '/api/v1/currency/rates': {
    get: {
      req: {
        /**
         * Base currency (e.g., USD)
         */
        base?: string
        /**
         * Query for a specific date
         */
        date?: string | null
        /**
         * End date for range query
         */
        endDate?: string | null
        /**
         * Start date for range query
         */
        startDate?: string | null
        /**
         * Target currency (e.g., ARS)
         */
        target?: string
      }
      res: {
        /**
         * Successful Response
         */
        200: ExchangeRatesResponse
      }
    }
  }
  '/api/v1/upload-jobs/{job_id}': {
    get: {
      req: {
        jobId: string
      }
      res: {
        /**
         * Job found
         */
        200: UploadJobPublic
      }
    }
  }
  '/api/v1/tags/': {
    get: {
      req: {
        limit?: number
        skip?: number
        userId?: string | null
      }
      res: {
        /**
         * Successful Response
         */
        200: TagsPublic
      }
    }
    post: {
      req: {
        requestBody: TagCreate
      }
      res: {
        /**
         * Successful Response
         */
        201: TagPublic
      }
    }
  }
  '/api/v1/tags/{tag_id}': {
    get: {
      req: {
        tagId: string
      }
      res: {
        /**
         * Successful Response
         */
        200: TagPublic
      }
    }
    patch: {
      req: {
        requestBody: TagUpdate
        tagId: string
      }
      res: {
        /**
         * Successful Response
         */
        200: TagPublic
      }
    }
    delete: {
      req: {
        tagId: string
      }
      res: {
        /**
         * Successful Response
         */
        204: void
      }
    }
  }
  '/api/v1/transaction-tags/': {
    post: {
      req: {
        requestBody: TransactionTagCreate
      }
      res: {
        /**
         * Successful Response
         */
        201: TransactionTagPublic
      }
    }
  }
  '/api/v1/transaction-tags/transaction/{transaction_id}': {
    get: {
      req: {
        transactionId: string
      }
      res: {
        /**
         * Successful Response
         */
        200: Array<TransactionTagPublic>
      }
    }
  }
  '/api/v1/transaction-tags/transaction/{transaction_id}/tag/{tag_id}': {
    delete: {
      req: {
        tagId: string
        transactionId: string
      }
      res: {
        /**
         * Successful Response
         */
        204: void
      }
    }
  }
  '/api/v1/rules/apply': {
    post: {
      req: {
        requestBody: ApplyRulesRequest
      }
      res: {
        /**
         * Successful Response
         */
        200: ApplyRulesResponse
      }
    }
  }
  '/api/v1/rules/': {
    post: {
      req: {
        requestBody: RuleCreate
      }
      res: {
        /**
         * Successful Response
         */
        201: RulePublic
      }
    }
    get: {
      req: {
        limit?: number
        skip?: number
      }
      res: {
        /**
         * Successful Response
         */
        200: RulesPublic
      }
    }
  }
  '/api/v1/rules/{rule_id}': {
    get: {
      req: {
        ruleId: string
      }
      res: {
        /**
         * Successful Response
         */
        200: RulePublic
      }
    }
    put: {
      req: {
        requestBody: RuleUpdate
        ruleId: string
      }
      res: {
        /**
         * Successful Response
         */
        200: RulePublic
      }
    }
    delete: {
      req: {
        ruleId: string
      }
      res: {
        /**
         * Successful Response
         */
        204: void
      }
    }
  }
  '/api/v1/utils/test-email/': {
    post: {
      req: {
        emailTo: string
      }
      res: {
        /**
         * Successful Response
         */
        201: Message
      }
    }
  }
  '/api/v1/utils/health-check/': {
    get: {
      res: {
        /**
         * Successful Response
         */
        200: boolean
      }
    }
  }
  '/api/v1/private/users/': {
    post: {
      req: {
        requestBody: PrivateUserCreate
      }
      res: {
        /**
         * Successful Response
         */
        200: UserPublic
      }
    }
  }
}
