"""add_credit_limit_to_credit_card

Revision ID: 053126351d61
Revises: 525d19d5f4f7
Create Date: 2026-02-04 22:40:46.373178

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "053126351d61"
down_revision = "525d19d5f4f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "credit_card",
        sa.Column("credit_limit", sa.DECIMAL(precision=32, scale=2), nullable=True),
    )
    op.add_column(
        "credit_card", sa.Column("limit_last_updated_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "credit_card",
        sa.Column(
            "limit_source", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credit_card", "limit_source")
    op.drop_column("credit_card", "limit_last_updated_at")
    op.drop_column("credit_card", "credit_limit")
    # ### end Alembic commands ###
