"""create_rules_tables

Revision ID: 4410df3f5247
Revises: d728a4c5b174
Create Date: 2026-02-02 21:19:55.830366

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "4410df3f5247"
down_revision = "d728a4c5b174"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rules",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("rule_id"),
    )
    op.create_index(op.f("ix_rules_user_id"), "rules", ["user_id"], unique=False)
    op.create_table(
        "rule_actions",
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("action_type", sa.Enum("ADD_TAG", name="actiontype"), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rules.rule_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.tag_id"],
        ),
        sa.PrimaryKeyConstraint("action_id"),
    )
    op.create_index(
        op.f("ix_rule_actions_rule_id"), "rule_actions", ["rule_id"], unique=False
    )
    op.create_table(
        "rule_conditions",
        sa.Column("condition_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column(
            "field",
            sa.Enum("PAYEE", "DESCRIPTION", "AMOUNT", "DATE", name="conditionfield"),
            nullable=False,
        ),
        sa.Column(
            "operator",
            sa.Enum(
                "CONTAINS",
                "EQUALS",
                "GT",
                "LT",
                "BEFORE",
                "AFTER",
                "BETWEEN",
                name="conditionoperator",
            ),
            nullable=False,
        ),
        sa.Column(
            "value", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column(
            "value_secondary",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column(
            "logical_operator",
            sa.Enum("AND", "OR", name="logicaloperator"),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rules.rule_id"],
        ),
        sa.PrimaryKeyConstraint("condition_id"),
    )
    op.create_index(
        op.f("ix_rule_conditions_rule_id"), "rule_conditions", ["rule_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rule_conditions_rule_id"), table_name="rule_conditions")
    op.drop_table("rule_conditions")
    op.drop_index(op.f("ix_rule_actions_rule_id"), table_name="rule_actions")
    op.drop_table("rule_actions")
    op.drop_index(op.f("ix_rules_user_id"), table_name="rules")
    op.drop_table("rules")
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS actiontype")
    op.execute("DROP TYPE IF EXISTS conditionfield")
    op.execute("DROP TYPE IF EXISTS conditionoperator")
    op.execute("DROP TYPE IF EXISTS logicaloperator")
    # ### end Alembic commands ###
