"""add_alias_to_credit_card

Revision ID: 525d19d5f4f7
Revises: e8f9a2b3c4d5
Create Date: 2026-02-04 14:46:42.607081

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "525d19d5f4f7"
down_revision = "e8f9a2b3c4d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "credit_card",
        sa.Column("alias", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credit_card", "alias")
    # ### end Alembic commands ###
