"""add_payment_tables_and_is_fully_paid_flag

Revision ID: 56238d1c7b22
Revises: ad3821a42367
Create Date: 2025-11-02 22:22:03.504576

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "56238d1c7b22"
down_revision = "ad3821a42367"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("statement_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=32, scale=2), nullable=True),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["card_statement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_statement_id"), "payment", ["statement_id"], unique=False
    )
    op.create_index(op.f("ix_payment_user_id"), "payment", ["user_id"], unique=False)

    # Add is_fully_paid column as nullable first
    op.add_column(
        "card_statement", sa.Column("is_fully_paid", sa.Boolean(), nullable=True)
    )

    # Set default value for existing records
    op.execute(
        "UPDATE card_statement SET is_fully_paid = false WHERE is_fully_paid IS NULL"
    )

    # Make the column NOT NULL after setting default values
    op.alter_column("card_statement", "is_fully_paid", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("card_statement", "is_fully_paid")
    op.drop_index(op.f("ix_payment_user_id"), table_name="payment")
    op.drop_index(op.f("ix_payment_statement_id"), table_name="payment")
    op.drop_table("payment")
    # ### end Alembic commands ###
