"""empty message

Revision ID: 62e03830fe2b
Revises: 56238d1c7b22
Create Date: 2025-11-02 22:32:53.390907

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "62e03830fe2b"
down_revision = "56238d1c7b22"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_statement_payment_link_payment_id"),
        table_name="statement_payment_link",
    )
    op.drop_index(
        op.f("ix_statement_payment_link_statement_id"),
        table_name="statement_payment_link",
    )
    op.drop_table("statement_payment_link")
    op.add_column("payment", sa.Column("statement_id", sa.Uuid(), nullable=False))
    op.add_column(
        "payment",
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
    )
    op.create_index(
        op.f("ix_payment_statement_id"), "payment", ["statement_id"], unique=False
    )
    op.create_foreign_key(None, "payment", "card_statement", ["statement_id"], ["id"])
    op.drop_column("payment", "notes")
    op.drop_column("payment", "payment_method")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment",
        sa.Column(
            "payment_method", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "payment",
        sa.Column("notes", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "payment", type_="foreignkey")
    op.drop_index(op.f("ix_payment_statement_id"), table_name="payment")
    op.drop_column("payment", "currency")
    op.drop_column("payment", "statement_id")
    op.create_table(
        "statement_payment_link",
        sa.Column("statement_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("payment_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "amount_applied",
            sa.NUMERIC(precision=32, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payment.id"],
            name=op.f("statement_payment_link_payment_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["card_statement.id"],
            name=op.f("statement_payment_link_statement_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "statement_id", "payment_id", name=op.f("statement_payment_link_pkey")
        ),
    )
    op.create_index(
        op.f("ix_statement_payment_link_statement_id"),
        "statement_payment_link",
        ["statement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_statement_payment_link_payment_id"),
        "statement_payment_link",
        ["payment_id"],
        unique=False,
    )
    # ### end Alembic commands ###
