"""create_upload_jobs_table

Revision ID: 68a5bc7ca648
Revises: aed3b4c73849
Create Date: 2026-02-03 13:48:09.968493

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "68a5bc7ca648"
down_revision = "aed3b4c73849"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upload_job",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column(
            "file_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "file_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("statement_id", sa.Uuid(), nullable=True),
        sa.Column(
            "error_message",
            sqlmodel.sql.sqltypes.AutoString(length=2000),
            nullable=True,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["credit_card.id"],
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["card_statement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_upload_job_card_id"), "upload_job", ["card_id"], unique=False
    )
    op.create_index(
        op.f("ix_upload_job_file_hash"), "upload_job", ["file_hash"], unique=False
    )
    op.create_index(
        op.f("ix_upload_job_status"), "upload_job", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_upload_job_user_id"), "upload_job", ["user_id"], unique=False
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_upload_job_user_id"), table_name="upload_job")
    op.drop_index(op.f("ix_upload_job_status"), table_name="upload_job")
    op.drop_index(op.f("ix_upload_job_file_hash"), table_name="upload_job")
    op.drop_index(op.f("ix_upload_job_card_id"), table_name="upload_job")
    op.drop_table("upload_job")
    # ### end Alembic commands ###
