"""add_color_to_tags

Revision ID: 891b81e824b6
Revises: 525d19d5f4f7
Create Date: 2026-02-04 23:17:58.468676

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "891b81e824b6"
down_revision = "525d19d5f4f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("color", sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tags", "color")
    # ### end Alembic commands ###
