"""add exchange_rate table

Revision ID: 9264e1aff838
Revises: e8f9a2b3c4d5
Create Date: 2026-02-04 14:59:16.776290

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "9264e1aff838"
down_revision = "e8f9a2b3c4d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange_rate",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_currency",
            sqlmodel.sql.sqltypes.AutoString(length=3),
            nullable=False,
            server_default="USD",
        ),
        sa.Column(
            "to_currency",
            sqlmodel.sql.sqltypes.AutoString(length=3),
            nullable=False,
            server_default="ARS",
        ),
        sa.Column("buy_rate", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("sell_rate", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column(
            "source",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
            server_default="cronista_mep",
        ),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exchange_rate_rate_date"), "exchange_rate", ["rate_date"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exchange_rate_rate_date"), table_name="exchange_rate")
    op.drop_table("exchange_rate")
    # ### end Alembic commands ###
