"""empty message

Revision ID: 9fae62a4aafd
Revises: 1a31ce608336
Create Date: 2025-11-02 17:24:14.542433

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "9fae62a4aafd"
down_revision = "1a31ce608336"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "label", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("tag_id"),
    )
    op.create_index(op.f("ix_tags_user_id"), "tags", ["user_id"], unique=False)
    op.create_table(
        "transaction",
        sa.Column("statement_id", sa.Uuid(), nullable=False),
        sa.Column("txn_date", sa.Date(), nullable=False),
        sa.Column(
            "payee", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("amount", sa.DECIMAL(precision=32, scale=2), nullable=True),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column(
            "coupon", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("installment_cur", sa.Integer(), nullable=True),
        sa.Column("installment_tot", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["card_statement.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transaction_statement_id"),
        "transaction",
        ["statement_id"],
        unique=False,
    )
    op.create_table(
        "transaction_tags",
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.tag_id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transaction.id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id", "tag_id"),
    )
    op.drop_table("item")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item",
        sa.Column(
            "description", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
            name=op.f("item_owner_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("item_pkey")),
    )
    op.drop_table("transaction_tags")
    op.drop_index(op.f("ix_transaction_statement_id"), table_name="transaction")
    op.drop_table("transaction")
    op.drop_index(op.f("ix_tags_user_id"), table_name="tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
