"""initial schema

Revision ID: a8ee30575e0c
Revises:
Create Date: 2026-02-10 10:25:02.160965

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "a8ee30575e0c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange_rate",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column(
            "to_currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column("buy_rate", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("sell_rate", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column(
            "source", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exchange_rate_rate_date"), "exchange_rate", ["rate_date"], unique=True
    )
    op.create_table(
        "user",
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "preferred_currency",
            sqlmodel.sql.sqltypes.AutoString(length=3),
            nullable=True,
        ),
        sa.Column("notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "ntfy_topic", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "credit_card",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("bank", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "brand",
            sa.Enum(
                "VISA", "MASTERCARD", "AMEX", "DISCOVER", "OTHER", name="cardbrand"
            ),
            nullable=False,
        ),
        sa.Column("last4", sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
        sa.Column("alias", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column(
            "default_currency",
            sqlmodel.sql.sqltypes.AutoString(length=3),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("credit_limit", sa.DECIMAL(precision=32, scale=2), nullable=True),
        sa.Column("limit_last_updated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "limit_source",
            sa.Enum("manual", "statement", name="limitsource"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_credit_card_user_id"), "credit_card", ["user_id"], unique=False
    )
    op.create_table(
        "rules",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("rule_id"),
    )
    op.create_index(op.f("ix_rules_user_id"), "rules", ["user_id"], unique=False)
    op.create_table(
        "tags",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "label", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("tag_id"),
    )
    op.create_index(op.f("ix_tags_user_id"), "tags", ["user_id"], unique=False)
    op.create_table(
        "card_statement",
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("close_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("previous_balance", sa.DECIMAL(precision=32, scale=2), nullable=True),
        sa.Column("current_balance", sa.DECIMAL(precision=32, scale=2), nullable=True),
        sa.Column("minimum_payment", sa.DECIMAL(precision=32, scale=2), nullable=True),
        sa.Column("is_fully_paid", sa.Boolean(), nullable=False),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("COMPLETE", "PENDING_REVIEW", name="statementstatus"),
            nullable=False,
        ),
        sa.Column(
            "source_file_path",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["credit_card.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_card_statement_card_id"), "card_statement", ["card_id"], unique=False
    )
    op.create_table(
        "rule_actions",
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("action_type", sa.Enum("ADD_TAG", name="actiontype"), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rules.rule_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.tag_id"],
        ),
        sa.PrimaryKeyConstraint("action_id"),
    )
    op.create_index(
        op.f("ix_rule_actions_rule_id"), "rule_actions", ["rule_id"], unique=False
    )
    op.create_table(
        "rule_conditions",
        sa.Column("condition_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column(
            "field",
            sa.Enum("PAYEE", "DESCRIPTION", "AMOUNT", "DATE", name="conditionfield"),
            nullable=False,
        ),
        sa.Column(
            "operator",
            sa.Enum(
                "CONTAINS",
                "EQUALS",
                "GT",
                "GTE",
                "LT",
                "LTE",
                "BEFORE",
                "AFTER",
                "BETWEEN",
                name="conditionoperator",
            ),
            nullable=False,
        ),
        sa.Column(
            "value", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column(
            "value_secondary",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column(
            "logical_operator",
            sa.Enum("AND", "OR", name="logicaloperator"),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rules.rule_id"],
        ),
        sa.PrimaryKeyConstraint("condition_id"),
    )
    op.create_index(
        op.f("ix_rule_conditions_rule_id"), "rule_conditions", ["rule_id"], unique=False
    )
    op.create_table(
        "payment",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("statement_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=32, scale=2), nullable=True),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["card_statement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_statement_id"), "payment", ["statement_id"], unique=False
    )
    op.create_index(op.f("ix_payment_user_id"), "payment", ["user_id"], unique=False)
    op.create_table(
        "transaction",
        sa.Column("statement_id", sa.Uuid(), nullable=False),
        sa.Column("txn_date", sa.Date(), nullable=False),
        sa.Column(
            "payee", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("amount", sa.DECIMAL(precision=32, scale=2), nullable=True),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column(
            "coupon", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("installment_cur", sa.Integer(), nullable=True),
        sa.Column("installment_tot", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["card_statement.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transaction_statement_id"),
        "transaction",
        ["statement_id"],
        unique=False,
    )
    op.create_table(
        "upload_job",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "PARTIAL",
                name="uploadjobstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "file_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "file_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("statement_id", sa.Uuid(), nullable=True),
        sa.Column(
            "error_message",
            sqlmodel.sql.sqltypes.AutoString(length=2000),
            nullable=True,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["credit_card.id"],
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["card_statement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "file_hash", name="uq_upload_job_user_file_hash"
        ),
    )
    op.create_index(
        op.f("ix_upload_job_card_id"), "upload_job", ["card_id"], unique=False
    )
    op.create_index(
        op.f("ix_upload_job_file_hash"), "upload_job", ["file_hash"], unique=False
    )
    op.create_index(
        op.f("ix_upload_job_status"), "upload_job", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_upload_job_user_id"), "upload_job", ["user_id"], unique=False
    )
    op.create_table(
        "transaction_tags",
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.tag_id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transaction.id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction_tags")
    op.drop_index(op.f("ix_upload_job_user_id"), table_name="upload_job")
    op.drop_index(op.f("ix_upload_job_status"), table_name="upload_job")
    op.drop_index(op.f("ix_upload_job_file_hash"), table_name="upload_job")
    op.drop_index(op.f("ix_upload_job_card_id"), table_name="upload_job")
    op.drop_table("upload_job")
    op.drop_index(op.f("ix_transaction_statement_id"), table_name="transaction")
    op.drop_table("transaction")
    op.drop_index(op.f("ix_payment_user_id"), table_name="payment")
    op.drop_index(op.f("ix_payment_statement_id"), table_name="payment")
    op.drop_table("payment")
    op.drop_index(op.f("ix_rule_conditions_rule_id"), table_name="rule_conditions")
    op.drop_table("rule_conditions")
    op.drop_index(op.f("ix_rule_actions_rule_id"), table_name="rule_actions")
    op.drop_table("rule_actions")
    op.drop_index(op.f("ix_card_statement_card_id"), table_name="card_statement")
    op.drop_table("card_statement")
    op.drop_index(op.f("ix_tags_user_id"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_rules_user_id"), table_name="rules")
    op.drop_table("rules")
    op.drop_index(op.f("ix_credit_card_user_id"), table_name="credit_card")
    op.drop_table("credit_card")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_exchange_rate_rate_date"), table_name="exchange_rate")
    op.drop_table("exchange_rate")
    # ### end Alembic commands ###
