"""remove_user_id_from_card_statements

Revision ID: ad3821a42367
Revises: e4f2a192ee24
Create Date: 2025-11-02 21:42:54.780071

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ad3821a42367"
down_revision = "e4f2a192ee24"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_card_statement_user_id"), table_name="card_statement")
    op.drop_constraint(
        op.f("card_statement_user_id_fkey"), "card_statement", type_="foreignkey"
    )
    op.drop_column("card_statement", "user_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "card_statement",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("card_statement_user_id_fkey"),
        "card_statement",
        "user",
        ["user_id"],
        ["id"],
    )
    op.create_index(
        op.f("ix_card_statement_user_id"), "card_statement", ["user_id"], unique=False
    )
    # ### end Alembic commands ###
