"""add_currency_status_fields_to_statements

Revision ID: aed3b4c73849
Revises: 4410df3f5247
Create Date: 2026-02-03 13:25:22.370379

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "aed3b4c73849"
down_revision = "4410df3f5247"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    statementstatus = sa.Enum("COMPLETE", "PENDING_REVIEW", name="statementstatus")
    statementstatus.create(op.get_bind(), checkfirst=True)

    # Add columns with server defaults for existing rows
    op.add_column(
        "card_statement",
        sa.Column(
            "currency",
            sqlmodel.sql.sqltypes.AutoString(length=3),
            nullable=False,
            server_default="ARS",
        ),
    )
    op.add_column(
        "card_statement",
        sa.Column("status", statementstatus, nullable=False, server_default="COMPLETE"),
    )
    op.add_column(
        "card_statement",
        sa.Column(
            "source_file_path",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
    )
    op.add_column(
        "credit_card",
        sa.Column(
            "default_currency",
            sqlmodel.sql.sqltypes.AutoString(length=3),
            nullable=False,
            server_default="ARS",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credit_card", "default_currency")
    op.drop_column("card_statement", "source_file_path")
    op.drop_column("card_statement", "status")
    op.drop_column("card_statement", "currency")

    # Drop the enum type
    sa.Enum(name="statementstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
