"""Initial migration with all models

Revision ID: c82f33e6cc89
Revises:
Create Date: 2025-11-30 19:25:00.260450

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "c82f33e6cc89"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "credit_card",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("bank", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "brand",
            sa.Enum(
                "VISA", "MASTERCARD", "AMEX", "DISCOVER", "OTHER", name="cardbrand"
            ),
            nullable=False,
        ),
        sa.Column("last4", sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_credit_card_user_id"), "credit_card", ["user_id"], unique=False
    )
    op.create_table(
        "tags",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "label", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("tag_id"),
    )
    op.create_index(op.f("ix_tags_user_id"), "tags", ["user_id"], unique=False)
    op.create_table(
        "card_statement",
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("close_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("previous_balance", sa.DECIMAL(precision=32, scale=2), nullable=True),
        sa.Column("current_balance", sa.DECIMAL(precision=32, scale=2), nullable=True),
        sa.Column("minimum_payment", sa.DECIMAL(precision=32, scale=2), nullable=True),
        sa.Column("is_fully_paid", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["credit_card.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_card_statement_card_id"), "card_statement", ["card_id"], unique=False
    )
    op.create_table(
        "payment",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("statement_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=32, scale=2), nullable=True),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["card_statement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_statement_id"), "payment", ["statement_id"], unique=False
    )
    op.create_index(op.f("ix_payment_user_id"), "payment", ["user_id"], unique=False)
    op.create_table(
        "transaction",
        sa.Column("statement_id", sa.Uuid(), nullable=False),
        sa.Column("txn_date", sa.Date(), nullable=False),
        sa.Column(
            "payee", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("amount", sa.DECIMAL(precision=32, scale=2), nullable=True),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column(
            "coupon", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("installment_cur", sa.Integer(), nullable=True),
        sa.Column("installment_tot", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["card_statement.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transaction_statement_id"),
        "transaction",
        ["statement_id"],
        unique=False,
    )
    op.create_table(
        "transaction_tags",
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.tag_id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transaction.id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction_tags")
    op.drop_index(op.f("ix_transaction_statement_id"), table_name="transaction")
    op.drop_table("transaction")
    op.drop_index(op.f("ix_payment_user_id"), table_name="payment")
    op.drop_index(op.f("ix_payment_statement_id"), table_name="payment")
    op.drop_table("payment")
    op.drop_index(op.f("ix_card_statement_card_id"), table_name="card_statement")
    op.drop_table("card_statement")
    op.drop_index(op.f("ix_tags_user_id"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_credit_card_user_id"), table_name="credit_card")
    op.drop_table("credit_card")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
