"""add_deleted_at_to_tags

Revision ID: d728a4c5b174
Revises: c82f33e6cc89
Create Date: 2026-02-02 20:32:22.459552

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d728a4c5b174"
down_revision = "c82f33e6cc89"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tags", "deleted_at")
    # ### end Alembic commands ###
