"""empty message

Revision ID: e4f2a192ee24
Revises: ee60af0cc9e0
Create Date: 2025-11-02 21:36:59.874141

"""

# revision identifiers, used by Alembic.
revision = "e4f2a192ee24"
down_revision = "ee60af0cc9e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
